### ISSUE TITLE
Dos vertx-redis-client support Redis Keyspace Notifications？Or it will be supportted in v3.6.0?

### ISSUE THREAD

**Issue by XiaohuChen** [vert-x3/vertx-redis-client#100]
### Version 3.5.0

* vert.x core:
* vert.x redis client:

Dos vertx-redis-client support Redis Keyspace Notifications？Or it will be supportted in v3.6.0?

**Comment by pmlopes** [comment]
@XiaohuChen have you tried to use the existing pub/sub infrastructure, I wasn't aware of this feature but it looks to me that it just relies on the existing pub/sub commands.

**Comment by XiaohuChen** [comment]
OK，thanks!
I fixed it. By default keyspace events notifications are disabled. Thanks !

**Comment by XiaohuChen** [comment]
OK thanks!
I fixed it. By default keyspace events notifications are disabled ! Thanks !
