### ISSUE TITLE
Sentinel Client Subscribe

### ISSUE THREAD

**Issue by rmmasse40** [vert-x3/vertx-redis-client#108]
### Version

* vert.x core: 3.5.1
* vert.x redis client: 3.5.1

### Context

I have found a problem with using a sentinels based client to subscribe to a channel. Once you execute the subscribe command the sentinel master resolve and connect code fails and goes into a infinite retry connect loop.

The culprit seems to be the call to "doCheckMaster" that is done by the connect logic. It issues an "INFO" command which is rejected by the redis server because it is in the subscribed context.

The error returned by the info command:

ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context

The simple fix is to modify the code:
  if (checkMaster) {
     doCheckMaster();
}

 to be:

  if (checkMaster && subscriptions == null) {
     doCheckMaster();
}

as a non-null subscriptions object seems to be what identifies a connection as a pubsub.

### Do you have a reproducer?

No

### Steps to reproduce

1. Create a redis client with sentinels
2. Create a consumer for the channel (optional)
3. Issue "subscribe" command

### Extra

I'm not very familiar with the contribution process so I'm starting out by just submitting the issue.

**Comment by pmlopes** [comment]
Could you make a pull request for this?

**Comment by rmmasse40** [comment]
Yes. I will do that.
