### ISSUE TITLE
 No handler waiting for message

### ISSUE THREAD

**Issue by mscofy** [vert-x3/vertx-redis-client#109]
### Version

* vert.x core:3.5.0
* vert.x redis client:3.5.0

### Context

I encountered an exception after the program has been running for some time:

Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: OK

Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: 1
Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: OK
Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: 1
Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: [Lio.vertx.redis.impl.Reply;@61757e1b
Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: [Lio.vertx.redis.impl.Reply;@3e492368

Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: [Lio.vertx.redis.impl.Reply;@12ec5614

Jun 01, 2018 9:40:51 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: [Lio.vertx.redis.impl.Reply;@58a367f4

Jun 01, 2018 9:40:54 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: [Lio.vertx.redis.impl.Reply;@2f865deb

Jun 01, 2018 9:41:17 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: [Lio.vertx.redis.impl.Reply;@4767ee21

Jun 01, 2018 9:42:28 AM io.vertx.redis.impl.RedisConnection
SEVERE: No handler waiting for message: [Lio.vertx.redis.impl.Reply;@37cb5c2f

### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant

**Comment by djblovecxc** [comment]
me too

**Comment by yoyoma214** [comment]
me too. I have ask the same question on stackoverflow site, see also
https://stackoverflow.com/questions/50697287/vertx-redis-clientno-handler-waiting-for-message

**Comment by pmlopes** [comment]
Can you provide a simple example reproducing the issue? That message is shown when redis server sends back some payload and no user code is expecting it. So it looks like there is a synchronization issue or some command is being handled incorrectly. The message itself does not let us know what is wrong, so without an example it will not be possible to debug.

**Comment by yoyoma214** [comment]
I meet the issue,but it's not a bug.see below
The problem has been solved. The reason for the above problem is that the connection has been reused and has not been closed. The solution is:`
 RedisClient redisClient = RedisClient.create(this.vertx, redisOptions);//do some thing; redisClient.close(h-{})...` for each session.
see also:
https://stackoverflow.com/questions/50697287/vertx-redis-clientno-handler-waiting-for-message
