### ISSUE TITLE
Support Redis 5.0 Stream API

### ISSUE THREAD

**Issue by leotu** [vert-x3/vertx-redis-client#110]
The new version of vertx-redis-client could consider to support Redis 5.0 Stream new feature.
https://redis.io/topics/streams-intro

**Comment by pmlopes** [comment]
Fixed by #101

**Comment by smoell** [comment]
Any news when Redis 5 Stream API will be supported by vertx-redis-client?

**Comment by whisper-bye** [comment]
+1

**Comment by pmlopes** [comment]
@smoell and @whisper-bye the pull request https://github.com/vert-x3/vertx-redis-client/pull/101 contains a new API that will become the default on 4.x. This new API improves the client performance, some tests show a 33% improvement, support for HA (sentinel) and cluster redis.

The client won't be opinionated so any existing or new API will be supported as long as the communication protocol doesn't change.

**Comment by pmlopes** [comment]
@smoell @leotu The PR has now a auto-generated API wrapper, which includes the `X`(Stream) commands, care to give a try?

**Comment by pmlopes** [comment]
This can be tested on 4.0.0 milestone 4
