### ISSUE TITLE
Provide possible result values for Redis commands

### ISSUE THREAD

**Issue by shawmanz32na** [vert-x3/vertx-redis-client#119]
When using vertx-redis-client, the "result" provided to result handlers don't match those listed by Redis.

As a specific example, attempting to set a value in Redis via `SETNX`, Redis states that the possible return values are `1` if the key was set, and `0` if it wasn't (see https://redis.io/commands/setnx). However, based on experimentation and the `testSetWithOptions2` test I found in https://github.com/vert-x3/vertx-redis-client/blob/master/src/test/java/io/vertx/test/redis/RedisClientTestBase.java, it appears that the values vertx-redis-client returns are `OK` if set, or `null` if not set.

```
redisClient.setWithOptions("someKey", "42", new SetOptions().setNX(true)), reply -> {
    // Reading Redis' docs, I'd expect to handle the reply like:
    if (reply == 1) {
        log("success");
    } else { // reply == 0
        log("failure - key already exists");
    }
    // But instead, I have to handle it like:
    // These values had be be manually discovered during code execution
    if ("OK".equals(reply) {
        log("success");
    } else { // reply == null
        log("failure - key already exists");
    }
});
```

The most straightforward solution would be to update the result provided to the `RedisClient`'s handlers to match what Redis specifies. Yes, this will be a notable amount of effort, since this will have to be manually inspected for each command, and yes, this will be a breaking change. That said, the next developer with Redis experience won't be confused by your implementation.

That said, I'm aware that high-effort, breaking changes are not a high priority, so I'd personally be satisfied if the results provided by vertx-redis-client for the various Redis commands were clearly documented, either in the [vertx-redis-client JavaDoc](https://vertx.io/docs/apidocs/) or in the [vertx-redis-client manual](https://vertx.io/docs/vertx-redis-client/java). I'd hope for some sort of tabular mapping from the (long) list of Redis commands to the possible result values.

**Comment by pmlopes** [comment]
New API does map to the protocol which solves this test with 4.0.0 milestone 4 and reopen if needed.
