### ISSUE TITLE
Support ReJSON

### ISSUE THREAD

**Issue by slinkydeveloper** [vert-x3/vertx-redis-client#121]
Support commands for [ReJSON plugin](https://oss.redislabs.com/rejson)

**Comment by pmlopes** [comment]
I believe that https://github.com/vert-x3/vertx-redis-client/pull/101should allow it to just work. As you would only need to do:

```java
client.send("JSON.SET", Args.args("foo", ".", "bar"), send -> {
  if (send.succeded()) {
    ...
```

But I haven't tested it...

**Comment by pmlopes** [comment]
@slinkydeveloper if you could verify it, we can have more trust in this code to replace the old one.

**Comment by pmlopes** [comment]
@slinkydeveloper this is now possible with: 

https://github.com/vert-x3/vertx-redis-client/pull/123/commits/420d40d1272ffbc52f5d56002f1dafaf9b231bdf#diff-957d3d34c4af930b972d0975e77123f8R254

Any non default command can be added by the end user.
