### ISSUE TITLE
Redis Client command handler on a different thread

### ISSUE THREAD

**Issue by pjlcastro** [vert-x3/vertx-redis-client#124]
### Version

* vert.x core: 3.5.4
* vert.x redis client: 3.5.4

### Context

Is there a way to change which thread the handler of a redis command to be executed?

I have a scenario where I want the worker verticle to wait until all redis commands are finished, so I used a CountDownLatch to track but since the handler runs on the same thread, if I use the CountDownLatch.await(), the handlers will never execute unless I interrupt the await().

Something like this:

CountDownLatch countdown = new CountDownLatch(10);

for (String value : values) {
  redisClient.sadd("key", value, result -> {
    countdown.countDown();
});
}

countdown.await();

Best regards and thanks for any help!

### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant

**Comment by pmlopes** [comment]
Event loop affinity has been fixed on 4.0.0 milestone 4
