### ISSUE TITLE
setex takes ttl as a long, RedisTransaction expire as an int

### ISSUE THREAD

**Issue by zacao** [vert-x3/vertx-redis-client#128]
### Version

* vert.x core: 3.6.2
* vert.x redis client: 3.6.2

### Context

```java
RedisTransaction expire(String key, int seconds, Handler<AsyncResult<String>> handler);
```

This is same issue like #71 about RedisClient

```java
  RedisClient expire(String key, long seconds, Handler<AsyncResult<Long>> handler);
```

**Comment by pmlopes** [comment]
New API helper is generated from redistribution metadata and fixes this, test with 4.0.0 milestone 4
