### ISSUE TITLE
Lazy Redis command queuing

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-redis-client#132]
The new redis client API is not lazy anymore and it might create usability issues when it comes to queue pending request when a service handle multiple requests.

When a service (Verticle) will create a Redis instance it will need to queue commands until the client is connected (it could be done initially but that would not work if the TCP connection is closed abruptly).

So the service will have to manage:

- concurrent connection to a redis instance
- queue redis commands until the connection succeeds or fails
- dequeue redis commands when the asynchronous connection result happens

We need to make this possible in the client itself instead of putting the burden on developers.

**Comment by vietj** [comment]
for the record here is what is required in vertx-config-store to make it work like before https://github.com/vert-x3/vertx-config/commit/aa3db574e7b3ea31c2325d040c4145bfc9a1c5fa

**Comment by vietj** [comment]
possible ways to achieve this:

- `createShared` like function that would handle this, where the user would then close the Redis after use to release it
- make a pool of redis connection (a proxy) of 1 connection (which is similar to the `createShared` option but is not static)

**Comment by KowalczykBartek** [comment]
hi @vietj - I want to play around that but just have a question - is RedisClient designed to be used only from the single thread ?
I didn't found nothing about that in docu, but looking at code seems to be not designed to be thread safe
```java
  @Override
  public Redis send(final Request request, Handler<AsyncResult<Response>> handler) {
    //stuff ....
    try {
      // encode the message to a buffer
      final Buffer message = ((RequestImpl) request).encode();
      // write to the socket
      waiting.offer(handler); /// <------ not atomic
      netSocket.write(message); ;// <------ not atomic
    } catch (RuntimeException e) {
      onException.handle(e);
    }
    return this;
  }
```
and
```java
  // waiting: commands that have been sent but not answered
  // the queue is only accessed from the event loop
  private final ArrayQueue waiting; // not thread safe also 
```

**Comment by KowalczykBartek** [comment]
Hi - 
What do you think about such approach https://github.com/KowalczykBartek/vertx-redis-client/pull/1 ?
I tried to integrate it with redis-config and it looks that it will work :) 

Please give me some feedback - so I can proceeded with the rest and with tests.

BTW: 
```
    final AtomicInteger count = new AtomicInteger(commands.size());
    final AtomicBoolean failed = new AtomicBoolean(false);
```
I think that this can be replaced with something that do not enforce write/read barrier - especially that this is always executed from event loop.

Thanks !

**Comment by pmlopes** [comment]
The branch: https://github.com/vert-x3/vertx-redis-client/tree/issues/pool implements a connection pool that implements what is discussed on this issue. Please keep an eye on it and feel free to comment.

**Comment by pmlopes** [comment]
Fixed on master with the connection pool
