### ISSUE TITLE
Redis close handler

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-redis-client#133]
Currently with the new API there is no way to be aware when a Redis instance will be closed (i.e TCP connection breaks).

The code using the client will connect to Redis but will not be aware when the Redis client needs to be _recycled_.

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-config/commit/aa3db574e7b3ea31c2325d040c4145bfc9a1c5fa#diff-93b55699bec48e62286148fa52d2cce8R96 where this would be used

**Comment by pmlopes** [comment]
Fixed on master
