### ISSUE TITLE
redis.rxHget breaks Observable contract, null element is passed to next operator. 

### ISSUE THREAD

**Issue by aygalinc** [vert-x3/vertx-redis-client#144]
### Version

* vert.x core: 3.7.0
* vert.x redis client: 3.7.0

### Context

I encountered an exception which looks suspicious while I use redis.rxHget(key1,field1).map(resp -> ...).subscribe() with the following assumption : key1 exist and field1 didn't exist in redis database. 
The map operator is called with a null, which break Observable contract. (https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls)
 
### Do you have a reproducer?

I use https://github.com/kstyrc/embedded-redis in my test to reproduce it.

**Comment by tsegismont** [comment]
Sounds like some `@Nullable` annotations are missing in the Vert.x Redis
client interface. Would you like to contribute the fix?

**Comment by aygalinc** [comment]
I can give a shot but I'm really not a Redis expert. I will see if I have time to do it next week. 

Do you have a list of all potential command that return can return null ?  

If i understand, you think that RedisApi must be rewrite from :  
 
`@Fluent
  default RedisAPI hget(String arg0, String arg1, Handler<AsyncResult<Response>> handler) {
    send(Command.HGET, arg0, arg1).setHandler(handler);
    return this;
  }
`
To : 

`@Fluent
  default RedisAPI hget(String arg0, String arg1, Handler<AsyncResult<@Nullable Response>> handler) {
    send(Command.HGET, arg0, arg1).setHandler(handler);
    return this;
  }
`
And the vertx generator handle these cases in different way ? 

Regards,

**Comment by tsegismont** [comment]
Le ven. 12 avr. 2019 à 17:00, Colin Aygalinc <notifications@github.com> a
écrit :

> I can give a shot but I'm really not a Redis expert. I will see if I have
> time to do it next week.
>

Cool!


> Do you have a list of all potential command that return can return null ?
>

No but I'm sure Paulo (the maintainer) can help.


> If i understand, you think that RedisApi must be rewrite from :
>
> @Fluent default RedisAPI hget(String arg0, String arg1,
> Handler<AsyncResult<Response>> handler) { send(Command.HGET, arg0,
> arg1).setHandler(handler); return this; }
> To :
>
> @Fluent default RedisAPI hget(String arg0, String arg1,
> Handler<AsyncResult<@Nullable Response>> handler) { send(Command.HGET,
> arg0, arg1).setHandler(handler); return this; }
>

Yes


>
> And the vertx generator handle these cases in different way ?
>

Exactly. The Rxified API will then return a Maybe instead of Single.

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vert-x3/vertx-redis-client/commit/b800db85ca1c8d1174f1cd30e97d8830b8c4807e
