### ISSUE TITLE
io.vertx.redis.RedisClient doesn't work anymore with 3.7.0?

### ISSUE THREAD

**Issue by bmwcmw** [vert-x3/vertx-redis-client#150]
### Version

* vert.x core: 3.7.0
* vert.x redis client: 3.7.0

### Context
We just upgraded to 3.7.0 from 3.6.3 and vertx won't connect to Redis anymore(circuit breaker never closed then).

The problem is resolved by just rollbacking the version to 3.6.3.

Normally this existing client is not deprecated so should be retro-compatible with 3.7.0.

http://vertx.io/blog/eclipse-vert-x-3-7-0-released/
https://vertx.io/docs/vertx-redis-client/java/

### Do you have a reproducer?
Run with this existing code:

`

    public RedisRepository(Vertx vertx, String redisHost, Integer redisPort, 
                           Integer redisDb, Integer timeout) {

        RedisOptions redisOptions = new RedisOptions()
                .setHost(redisHost)
                .setPort(redisPort)
                .setSelect(redisDb);
        redisOptions.setIdleTimeout(1);
        this.redis = RedisClient.create(vertx, redisOptions);

        CircuitBreakerOptions circuitBreakerOptions = new CircuitBreakerOptions()
                .setMaxFailures(5).setTimeout(100)
                .setFallbackOnFailure(true)
                .setResetTimeout(timeout);

        this.circuitBreaker = CircuitBreaker
                .create("", vertx, circuitBreakerOptions)
                .closeHandler(event -> log.info(" Circuit Breaker closed"))
                .openHandler(event -> log.info(" Circuit Breaker opened"))
                .halfOpenHandler(event -> log.info(" Circuit Breaker half opened"));
    }
`

### Extra
Problem resolved by rollbacking vertx&vertx-redis-client to 3.6.3

Thanks.

**Comment by ukr15** [comment]
same problem like #148

**Comment by bmwcmw** [comment]
Closing this one as it duplicates https://github.com/vert-x3/vertx-redis-client/issues/148
