### ISSUE TITLE
3.7.0 setBinary broken

### ISSUE THREAD

**Issue by marcust** [vert-x3/vertx-redis-client#151]
### Version

* vert.x core: 3.7.0
* vert.x redis client: 3.7.0

### Context

I'm trying to write binary into redis (via `rxSetBinary`) and reading again, but the value that actual ends up in redis is `"[B@57f2e67"`.

I'm not sure about the semantics, but in `RedisClientImpl` (https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/impl/RedisClientImpl.java#L96) the byte array from the buffer is added directly into the `result` list and in https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/impl/RedisClientImpl.java#L112 `toString()` is called on it. That explains the behaviour, but I don't get the intention.

**Comment by pmlopes** [comment]
Fixed on master and 3.7.1
