### ISSUE TITLE
If connection to redis break, RedisClient will not retry auto establish connection again.

### ISSUE THREAD

**Issue by liukch** [vert-x3/vertx-redis-client#154]
### Version

* vert.x core: 3.7.0
* vert.x redis client: 3.7.0

### Context

I use examples.RedisExamples#example10 to attempt reconnection, but when the connection to redis is broken, the io.vertx.redis.client.impl.RedisClient#connect will call io.vertx.core.net.impl.NetClientImpl#close, When the example10.attemptReconnect loop goes to the second time, an IllegalStateException will be threw. 

This lead to when redis restores the connection, netClient can't auto reestablish connect to redis.
So the connection can only be reestablished by calling io.vertx.redis.client.Redis#createClient again.

I think if RedisClient should offer a method like netSocket.exceptionHandler, in order to open an entrance to auto retry reestablish the connection to redis.
Is there any deviation in my understanding of this part, there are good way to deal with this problem?

**Comment by wbkys** [comment]
if(handler.failed()) {
	attemptReconnect(3, message);
 }

private void attemptReconnect(int retry, Message<JsonObject> message) {
    if (retry > MAX_RECONNECT_RETRIES) {
      // we should stop now, as there's nothing we can do.
    	log.error("redis over!");
    	message.reply(null);
    } else {
      // retry with backoff up to 1280ms
      long backoff = (long) (Math.pow(2, MAX_RECONNECT_RETRIES - Math.max(MAX_RECONNECT_RETRIES - retry, 9)) * 500);
	  
      vertx.setTimer(backoff, timer -> Redis.createClient(vertx, options)
    	      .connect(onConnect -> {
    	          if (onConnect.succeeded()) {
    	            redis = RedisAPI.api(onConnect.result());
    	            log.info("redis: attemptReconnect");
    	          }else {
    	          	attemptReconnect(retry + 1, message);
    	          	log.error("redis attemptReconnect:" + onConnect.cause().getMessage());
    	          }
    	          message.reply(null);
    	        })
    	      );
    }
  }

**Comment by wbkys** [comment]
https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/examples/RedisExamples.java

**Comment by liukch** [comment]
@wbkys I use examples.RedisExamples#example10 to attempt reconnection!
But if redis tcp connection break, this will not work.

**Comment by wbkys** [comment]
if（
          handler.failed （））{ attemptReconnect（3，message）; 
}

**Comment by liukch** [comment]
@wbkys As I said in issue context,
 I don't think call io.vertx.redis.client.Redis#createClient to build a new Redis object is good way to reestablish a connection, may be RedisClient should offer a method like netSocket.exceptionHandler()?

**Comment by wbkys** [comment]
Sorry, I didn't find out. I need to see it.

**Comment by pmlopes** [comment]
The new pooled mode solves this.
