### ISSUE TITLE
when using setPort/setHost methods in a RedisOptions object , then using tojson , the resulting json object doesnot have the port and host parameters , that caused the RX redis client always to use the default port 

### ISSUE THREAD

**Issue by mmhegazy** [vert-x3/vertx-redis-client#157]
### Version 
3.7.0/3.7.1
* vert.x core:3.7.0/3.7.1
* vert.x redis client:io.vertx.reactivex.redis.RedisClient

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

* Link to github project/gist

### Steps to reproduce

1.RedisOptions redisopt=new RedisOptions().setHost(host).setPort(port)
2. redis = RedisClient.create(vertx,redisopt.toJson());
3. always connecting to the default port and host 
4. ...

### Extra

* Anything that can be relevant

**Comment by pmlopes** [comment]
New API uses the new official connection url scheme
