### ISSUE TITLE
Don't pass "QUEUED" responses to handlers

### ISSUE THREAD

**Issue by abonander** [vert-x3/vertx-redis-client#168]
When executing `ZREM` it appears to respond initially with `"QUEUED"` which isn't really helpful and also causes an exception in the handler when trying to convert the response to a long [to read the return value](https://redis.io/commands/zrem#return-value).

**Comment by pmlopes** [comment]
How are you getting that result? Could you provide a code snippet? 

QUEUED is coming from redis directly usually it means you're inside a transaction, so we need a bit more information here...

**Comment by abonander** [comment]
Ah, yes it is occurring inside `MULTI`, that was my mistake. I forgot the results are not returned until `EXEC` is sent.
