### ISSUE TITLE
 Redis waiting Queue is full 

### ISSUE THREAD

**Issue by Halooooooo** [vert-x3/vertx-redis-client#171]
### Version

* vert.x core:3.7.1
* vert.x redis client:3.7.1

### Context

I encountered an exception which looks suspicious while ...
i use verx to decr redis key but vertx throw a throwable 
io.vertx.core.impl.NoStackTraceThrowable:  Redis waiting Queue is full .
and tps 20000-30000
i try to increase MaxWaitingHandlers but not work, i want increase vertx-reids tps 

### Extra

* Anything that can be relevant
Vertx vertx = Vertx.vertx();
        Redis connect = Redis.createClient(vertx, new io.vertx.redis.client.RedisOptions().addEndpoint(SocketAddress.inetSocketAddress(7000,"10.124.164.104")).setPassword("halo53").setMaxWaitingHandlers(40*10000).setMaxNestedArrays(240))
                .connect(onConnect -> {
                    if (onConnect.succeeded()) {
                        Redis client = onConnect.result();
                    }
                });
        AtomicInteger atomicInteger = new AtomicInteger(0);

        final RedisAPI redis = RedisAPI.api(connect);
        while(true){
            redis.decr("text",event -> {
                if(event.failed()){
                    event.cause().printStackTrace();
                    System.out.println("failed"+atomicInteger.incrementAndGet());
                }
            });
        }

**Comment by pmlopes** [comment]
There's something not correct with your snippet. Doing an infinite loop sending commands to redis, will without of a doubt fail after a while. Your CPU can cycle faster the loop and push to the queue a command than the OS + network layer can deliver and receive a reply from redis. With will not increase your TPS as the requests have to wait for a reply.

The old client had an unbounded queue so you wouldn't see the problem unless you would run out of memory, now you do. If you want to increase the TPS you will need more clients (which we're working on having a connection pool on #156 )
