### ISSUE TITLE
Multi-thread with sync operation performance like single-thread

### ISSUE THREAD

**Issue by caixinning** [vert-x3/vertx-redis-client#176]
### Version

* vert.x core:3.7.0
* vert.x redis client:3.7.0

### Context
I try to use vertx-redis-client in sync, i guess it would hurt performance a lot, but actually the performance was extremely slow,  almost equals to one thread serially.
Sometimes it throw 'No handler waiting for message'.

Here is my test code:

[RedisBenchmarkDemo.java.zip](https://github.com/vert-x3/vertx-redis-client/files/3459533/RedisBenchmarkDemo.java.zip)

**Comment by pmlopes** [comment]
The client is written in an asynchronous programing model. Forcing it to be synchronized will serialize all commands plus connection handling which you observe as slow.

In order to use it in a sync environment you should have 1 eventloop per thread and a client per thread.
