### ISSUE TITLE
Getting exception while using the redis client to retrieve 4000 records Asynchronously 

### ISSUE THREAD

**Issue by mmhegazy** [vert-x3/vertx-redis-client#178]
### Version

* vert.x core: 3.7.1
* vert.x redis client: 3.7.1

### Context

I encountered an exception that looks suspicious while using the redis client to retrieve 4000 records concurently.

### Do you have a reproducer? No 

* Link to github project/gist

### Steps to reproduce

1. Insert 4000 records into the redis DB 
2. retrieve the 4000 records in an aconcurrent way 

Aug 29 18:29:19 rzn1-ep1 sh[699]: java.lang.IndexOutOfBoundsException
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.vertx.redis.client.impl.ArrayQueue.offer(ArrayQueue.java:56)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.vertx.redis.client.impl.RedisClient.lambda$send$10(RedisClient.java:257)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Aug 29 18:29:19 rzn1-ep1 sh[699]:         at java.lang.Thread.run(Unknown Source)

### Extra

* Anything that can be relevant

**Comment by wbkys** [comment]
options = new RedisOptions().setMaxWaitingHandlers(5000)

**Comment by pmlopes** [comment]
the offer is now guarded by a full check so you should get a better error message. Also like it was commented increase the max waiting handlers limit to allow such a big queue of requests in transit.
