### ISSUE TITLE
How does redis set an empty string

### ISSUE THREAD

**Issue by 13779983327** [vert-x3/vertx-redis-client#179]
### Version 3.8.0
code:
redis.set(Arrays.asList("test",""), res->{
            if (res.succeeded()) {
                System.out.println("set result = " + res.result());
            } else {
                res.cause().printStackTrace();
            }
        });

get test result is 
$0

"

I found it in the code ：RequestImpl.java
 if (arg.length() == 0) {
      args.add(EMPTY_BULK);
      return this;
    }

I don't know if it has anything to do with this code

**Comment by pmlopes** [comment]
Indeed, those constants are wrong as they were used before cluster support was available.
