### ISSUE TITLE
Redis Cluster always connected to 127.0.0.1

### ISSUE THREAD

**Issue by gillbates** [vert-x3/vertx-redis-client#181]
Hi Vertx Devs,

when I try following code with vertx 3.8.0:

Vertx vertx = Vertx.vertx(); RedisClient redis = RedisClient.create(vertx, new RedisOptions().setSentinels(List.of("192.168.5.20:8400", "192.168.5.20:8401", "192.168.5.20:8402")).setMasterName("MASTER_NAME")); Future<JsonArray> future = Future.future(); redis.keys("*", future); future.setHandler(res -> { if (res.succeeded()) { System.out.println(res.result()); } else { res.cause().printStackTrace(); } });
it always throw an following exception:

`
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)

`

But actually nothing is listening on 127.0.0.1:6379
Maybe its an internal issue ...

 @gillbates

**Comment by KoellGerhard** [comment]
You are useing the wrong namespace. Don't use RedisClient.create from io.vertx.redis.*

Use Redis.createClient and the RedisOptions from the io.vertx.redis.**client**.* namespace instead 
The set the type to cluster and add endpoints

Gerhard
