### ISSUE TITLE
Redis connection URI support

### ISSUE THREAD

**Issue by Gaket** [vert-x3/vertx-redis-client#183]
### Version

* vert.x core: 3.8.1
* vert.x redis client: 3.8.1

### Context

I've started learning Vert.x, mostly I have Android dev experience.

Trying to connect a Redis instance to Vert.x Verticle. The most convenient way for me would be to simply user Redis URI, as the first variant here, in another Redis library: https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details

However, I can't find such an option neither in `RedisOptions`, neither in docs: http://vertx.io/docs/vertx-redis-client/java/

Does this library really not have possibility of using a connection URI?

**Comment by pmlopes** [comment]
In master there's support for redis uri, however there's no standard but as master hasn't been released in a final release we could verify and see if we could align the format.

**Comment by Gaket** [comment]
Actually, URI string support was added in Redis 4.0.3. Here you can find [a commit message](https://raw.githubusercontent.com/antirez/redis/4.0/00-RELEASENOTES) (try looking for "-u" in the log), and [here](https://redis.io/topics/rediscli) you can find a description.

I will be happy to contribute, adding a `RedisOptions.setConnectionUri(String connectionUri)` that will parse the URI through `URI.create()` and set according fields of the `RedisOptions`. Also, addition of such a constructor may be considered as well, giving the ease of using a ready URI, often provided by Redis cloud hosts.

Of course, tests will be added as well.

**Comment by pmlopes** [comment]
@Gaket great, please do and ping me if there's any need issue. Note that RedisURI is in the `impl` package so feel free to modify it to properly implement the URI as redis 4.0.3 specifies.

**Comment by Gaket** [comment]
Sorry, had a couple of busy weeks. Going to implement it this Sunday / next Monday. Just for your information.

**Comment by Gaket** [comment]
In RedisURI I renamed the `address` field to `connectionString`, similar to the way it is called in MongoDb: https://docs.mongodb.com/manual/reference/connection-string/

There is a `RedisOptions.setEndpoint(String endpoint)` method that actually behaves (after a few small touches) as a `RedisOptions.setConnectionStringUri(String connectionStringUri)`.

1) Can I rename this public api parameter name and it's javadoc? 

2) Should I rename the method itself or should I create a new method with the proposed name (`RedisOptions.setConnectionStringUri(String connectionStringUri)`) but actually doing the same thing? Or let's just update the Javadoc?

**Comment by pmlopes** [comment]
Please create a new one and deprecate the old one. So if someone was already using it it won't break.

**Comment by pmlopes** [comment]
Already on rc4
