### ISSUE TITLE
Shall we add `stream/parallelStream` in `Response`?

### ISSUE THREAD

**Issue by arniu** [vert-x3/vertx-redis-client#186]

**Comment by Globegitter** [comment]
Is it possible to actually stream the results back from redis? Maybe not on a `get` call, but at least on an `mget` call it could be very interesting to get each item back as it comes in.

**Comment by pmlopes** [comment]
The `RedisConnection` implements the `ReadStream` interface, it will stream any event (from a pub/sub) setup to the handler that is supplied.

The `Response` doesn't for the fact that a Redis response is sent as one message from the server back to the client.

In the case of a `mget` the server does not send a entry one by one, it sends a `multi bulk` message with the total number of entries, plus all the entries.

Implementing streaming on the response would then make the streaming an *artificial* construct as that is not how the protocol works.

How would the case of error handling be done in this case, if a `mget` says it contains 4 replies but the server aborts the connection after 1 reply? Using a plain stream you can't rollback to the previous state.

**Comment by arniu** [comment]
Without `stream`, it's really boring to handle the `multi ... exec` response.

**Comment by pmlopes** [comment]
We can also look at the issue from a different perspective. Given that result implements `Iterable` we could have a stream that streams from that iterable, not as results flow over the wire for the reasons stated above. Would that be a good compromise?

**Comment by arniu** [comment]
While to get a `Stream`, we have to write `StreamSupport.stream(response.spliterator(), false)` manually, which is really boring.

So, how about to add `stream/parallelStream`, just like what `java.util.Collection` does?

**Comment by pmlopes** [comment]
@arniu that is what I was trying to suggest.
