### ISSUE TITLE
Context difference

### ISSUE THREAD

**Issue by zenios** [vert-x3/vertx-redis-client#187]
### Version

* vert.x core:4.0.0-milestone2
* vert.x redis 4.0.0-milestone2

### Context

When acquiring a connection from Redis client the handler is called on a different context instead of the context used when calling.

Is that intentional? 

Do we need to execute runOnContext inside the handler in order to return back to the calling context?

**Comment by pmlopes** [comment]
I'll fix it soon. The goal is to execute on the right context.
