### ISSUE TITLE
Redis Sentinel support

### ISSUE THREAD

**Issue by imavroukakis** [vert-x3/vertx-redis-client#19]
Hi there, I was going through the source of RedisConnection and there's nothing in there to suggest Redis Sentinel is supported. Would you mind confirming?

Thanks!

**Comment by pmlopes** [comment]
No, sentinel is not supported out of the box, it does however try to reconnect to redis if the connection is broken.

**Comment by imavroukakis** [comment]
Thanks Paulo, any plans of adding it?

**Comment by pmlopes** [comment]
Not at the moment mostly because I am not familiar with sentinel, however we do accept pull requests 😉

**Comment by pmlopes** [comment]
If you think this is a important feature please vote for it here:

https://groups.google.com/forum/#!topic/vertx/5oDpfe3YhfA

**Comment by ajaysarda** [comment]
Sent a pull request for sentinel support: https://github.com/vert-x3/vertx-redis-client/pull/35.

**Comment by ajaysarda** [comment]
Sent a pull request for sentinel support: #36

**Comment by mikand13** [comment]
Hey, any progress on this? If not, any way I can help?

**Comment by pmlopes** [comment]
@mikand13 if you can help, please do, the PR is stalled for a long time mostly because of a huge merge conflict, if you are willing to help, please take it over!

**Comment by imavroukakis** [comment]
https://github.com/vert-x3/vertx-redis-client/pull/36

**Comment by pmlopes** [comment]
Yes that is the original PR related to this issue. As you can see it is not complete, it has conflicts and apparently it does not follow the redis requirements as @brianjcj wrote.

**Comment by imavroukakis** [comment]
@mikand13 shall we review?

**Comment by mikand13** [comment]
@pmlopes @imavroukakis I have a release coming up in the near future so i cant commit to this immediatly but its something we are going to want and need pretty soon.

So give me a couple of weeks to look into the inner workings of redis-client, the redis specs and the pull request and ill get back to you. Sound ok?

**Comment by orre** [comment]
I have created a new pull request for Sentinel support #80 . I think it corrects the shortcomings noted so far (in particular not supporting the Sentinel Client Guidelines). Hope it will make it all the way this time...

**Comment by pmlopes** [comment]
@orre Thanks!

**Comment by manucr619** [comment]
Is there any update on this ??

**Comment by pmlopes** [comment]
This is a major new feature we should try to get it in for 3.5, of course we need to review it first. Currently we're busy with 3.4.2 which should be all about fixing bugs and no real new features.

**Comment by mariuszpatyk** [comment]
Hello to everyone, very good work! After using this redis-client implementation for a while I found that the connection with the sentinel instances in RedisConnection is not being closed after resolving master address by RedisMasterResolver.getMasterAddressByName. For example, when I create a lot of RedisClient instances (because I need it for running transactions in separate sessions; of course after finishing and closing transaction I call close on RedisClient instance) it is very easy to reach the client limit in sentinel, because of rising number of dead RedisMasterResolver connections. So I added method close() in RedisMasterResolver which is called by RedisConnection, and this resolved this problem. I'm running now this code in production environment and it works fine.

**Comment by pmlopes** [comment]
@mariuszpatyk could you provide your patch so we can review and merge?

**Comment by mariuszpatyk** [comment]
ok
[pull_80_mp.patch.txt](https://github.com/vert-x3/vertx-redis-client/files/1119406/pull_80_mp.patch.txt)

**Comment by pmlopes** [comment]
sentinel PR merged and patch applied: see: https://github.com/vert-x3/vertx-redis-client/commit/09835c1a9b4e1a3ac1769e253d1994d3f3a06711

**Comment by litpangchen** [comment]
Hi Sir , May i know when will release version 3.5.0 vertx-redis client which will support sentinel , failover implementation mode? Thank ~

**Comment by manucr619** [comment]
3.5.0 Vertx is released .. Any Updates Regarding the Sentinel Support ? @pmlopes

**Comment by biolearning** [comment]
was it really incorporated in 3.5.0？ I do not see it is referred in the doc.

**Comment by manucr619** [comment]
Can i write a jar file in pure java for Sentinel Connection and can i call in that file for Getting the Redis Master ??

**Comment by orre** [comment]
RedisOptions has all the stuff you need to configure the RedisClient for
Sentinel. In particular you have addSentinel and setMasterName.

Den tor 9 nov 2017 08:24Manu C. Rajan <notifications@github.com> skrev:
