### ISSUE TITLE
RuntimeException: Number of key is not even

### ISSUE THREAD

**Issue by badrazizi** [vert-x3/vertx-redis-client#197]
### Version

* vert.x core:  3.8.2
* vert.x redis client:  3.8.2

### Context

if redis have any odd number of keys 3,5,7.. i get runtime exception.
i have been looking at the source code and i found https://github.com/vert-x3/vertx-redis-client/blob/21075c83eff35119e2af8c5b57d8b7f1fd5628be/src/main/java/io/vertx/redis/client/impl/types/MultiType.java#L77

```java
@Override
public Set<String> getKeys() {
  if (replies.length % 2 == 0) {
    final Set<String> keys = new HashSet<>();
    for (int i = 0; i < replies.length; i+=2) {
      keys.add(replies[i].toString());
    }

    return keys;
  }
  throw new RuntimeException("Number of key is not even");
}
```
i really don't understand why it's should be even number

### Do you have a reproducer?

no

### Steps to reproduce

if i run the code below and redis have odd number of keys will get runtime exception
```Kotlin
redisAPI.keys("Posts.*") { ctx ->
    if(ctx.succeeded()) {
        val result = ctx.result()
        for(key in result.keys) {
            println(key)
        }
    } else {
        println(ctx.cause().message)
    }
}
```

### Extra

* Anything that can be relevant

**Comment by pmlopes** [comment]
@badrazizi they `keys` method is a utility when working with hashes, for, example, when you execute a `hmget` command, in this case the response will be:

```
key1
value1
key2
value2
...
```

So the number of keys must be even and you know the even number is the `key` and the odd number is the `value`.

Now you want to iterate the multi response, in this case, there are no keys involved, just values. The response object implements the `Iterable` interface so you can do:

```
val keys = ctx.result()
for(result in keys) {
  println(result)
}
```
