### ISSUE TITLE
Movable key commands on cluster client.

### ISSUE THREAD

**Issue by wem** [vert-x3/vertx-redis-client#198]
### Version

* vert.x core: 3.8.3
* vert.x redis client: 3.8.3

### Context
Is the reason the clustered client can not handle some kind of commands like EVAL, GEO... (those, they are flagged as movable), that they can contain multiple keys and therefore maybe needs to get validated against the target hash slot?

**Comment by pmlopes** [comment]
Eval for example must be run on all nodes. The "fix" would be to write a custom handle for it like:

https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java#L70

**Comment by wem** [comment]
Are you sure that EVAL must run against all nodes? The Redis cluster spec says:

> Implemented subset
> Redis Cluster implements all the single key commands available in the non-distributed version of Redis. Commands performing complex multi-key operations like Set type unions or intersections are implemented as well as long as the keys all hash to the same slot.
> 
> Redis Cluster implements a concept called hash tags that can be used in order to force certain keys to be stored in the same hash slot. However during manual resharding, multi-key operations may become unavailable for some time while single key operations are always available.
...
And
...
> Since cluster nodes are not able to proxy requests, clients may be redirected to other nodes using redirection errors -MOVED and -ASK. The client is in theory free to send requests to all the nodes in the cluster, getting redirected if needed, so the client is not required to hold the state of the cluster. However clients that are able to cache the map between keys and nodes can improve the performance in a sensible way.

As i understand (and tested with near all of the movable flagged commands and https://github.com/Grokzen/docker-redis-cluster) commands with mutliple keys they target different hash slots 
will fail anyway with "(error) CROSSSLOT Keys in request don't hash to the same slot" like `redis-cli -h localhost -p 7000 "redis.call('SET', KEYS[1], ARGV[1]) redis.call('SET', KEYS[2], ARGV[1])" 2 {hash_tag}.key {other-hash_tag}.key value`.

So i think those commands can be implemented straight forward, ideal but optional with a validation of the hash slots before command execution. Or i am wrong?

**Comment by pmlopes** [comment]
Hi, `eval` is not on the list:

https://github.com/vert-x3/vertx-redis-client/blob/3.8/src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java#L124-L129

So it's a error on my side, the issue here is to implement the right behavior of the commands on that list, we would also remove that restriction and let them run as they are and pass the error back

**Comment by wem** [comment]
Hi ... ah, the movable flag of the commands https://github.com/vert-x3/vertx-redis-client/blob/2d2770ce35fa8a9c402ed841c9f62974dbc94f1f/src/main/java/io/vertx/redis/client/impl/CommandImpl.java#L38 is related to the command information (Movable keys) of https://redis.io/commands/command

If it's welcome, i will do a PR for processing and key slot validation of those commands. Would that okay for you? And if yes, which should be the target branch ... 3.8.4?

**Comment by pmlopes** [comment]
Fell free tot help on the!

**Comment by pmlopes** [comment]
Already on rc4
