### ISSUE TITLE
Redis connection pool support?

### ISSUE THREAD

**Issue by StarWindMoonCloud** [vert-x3/vertx-redis-client#200]
### Version

* vert.x core: 3.8.3
* vert.x redis client: 3.8.3

### Context

I tried out RedisClient, turned out it's single connection when put onto prod, which is not cool in terms of high performance, wondering if there is any easy to use connection pool like JedisPool available

**Comment by pmlopes** [comment]
Connection pooling will be available in 4.0 (it's already on master). Note that redis is single threaded, so using a single connection will give you good results. Connections should be reused across requests, and this is where the connection pooling in master enters. It allows you to forget about the connection management as reuse, but for top performance, a always active connection will give you even better results.

**Comment by StarWindMoonCloud** [comment]
@pmlopes is it available in version 4.0.0-milestone3? If so, any good example?
