### ISSUE TITLE
Redis connection pool bug for 4.0.0-milestone3  ?

### ISSUE THREAD

**Issue by cp19861214** [vert-x3/vertx-redis-client#207]
who  can give me a example "Redis connection pool" ?
I try use Redis connection pool myself ,but I found a bug, I want to loop 10 times,but when run 3 times it's bloked !
     
  RedisOptions config = new io.vertx.redis.client.RedisOptions();
        config.setEndpoints(endpoints);
        config.setType(RedisClientType.SENTINEL);
        config.setMasterName(masterName);
        config.setRole(RedisRole.MASTER);
         config.setMaxPoolSize(60);
        config.setMaxPoolWaiting(100);
        config.setPoolRecycleTimeout(2000);
      
        NetClientOptions nco = new NetClientOptions();
        nco.setConnectTimeout(connectTimeout);
        nco.setIdleTimeout(idleTimeout);
        nco.setReconnectInterval(2000);
        nco.setReconnectAttempts(3);
        config.setNetClientOptions(nco);
        Redis client = Redis.createClient(vertx, config);
         
        for (int i = 0;i< 10;i++) {
	         client.connect(c -> {
	            if (c.succeeded()) {
	                redis.send(Request.cmd(Command.GET).arg(key),r->{
	                		System.out.println("ok");
	                });
	            } 
	           });
         }

**Comment by cp19861214** [comment]
help me !!!

**Comment by pmlopes** [comment]
Hi @cp19861214 many connection pool bugs have been fixed on master, could you try to use a current snapshot instead and see if the issue you're seeing is fixed?

Just create or update your local maven `~/.m2/settings.xml` to have:

```xml
<settings>
  <profiles>
    <profile>
      <id>allow-snapshots</id>
      <activation><activeByDefault>true</activeByDefault></activation>
      <repositories>
        <repository>
          <id>snapshots-repo</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
  </profiles>

</settings>
``` 

This should allow you to have access to CI snapshots so you can use `4.0.0-SNAPSHOT` versions.

**Comment by cp19861214** [comment]
I try use 4.0.0-SNAPSHOT version ,but I still see the  issue , could you give me a full example with redis connecton pool ?

**Comment by cp19861214** [comment]
@pmlopes  Could you give me a full example with redis connecton pool  ?

**Comment by pmlopes** [comment]
Please see the test:

https://github.com/vert-x3/vertx-redis-client/blob/master/src/test/java/io/vertx/redis/client/test/RedisPooledTest.java

Also note that for faster support you can join the chat:

https://gitter.im/eclipse-vertx/vertx-users
