### ISSUE TITLE
brpoplpush should have Handler<AsyncResult<JsonObject>> parameter

### ISSUE THREAD

**Issue by yanai** [vert-x3/vertx-redis-client#21]
The current implementation for brpoplpush has Handler<AsyncResult<Void>> as it's last parameter. With existing singniture, there is no way to get the popped element in a single atomic operation.

The api should have the  Handler<AsyncResult<JsonObject>> parameter instead.

**Comment by pmlopes** [comment]
thanks for noticing, i will fix asap

**Comment by pmlopes** [comment]
fixed on master

**Comment by yanai** [comment]
Great, Thanks
