### ISSUE TITLE
ArrayIndexOutOfBoundsException in ArrayQueue.java

### ISSUE THREAD

**Issue by mariuszpatyk** [vert-x3/vertx-redis-client#213]
### Version
vert.x core:3.8.5
vert.x redis client:3.8.5

### Context
This error occures **always** after more then Integer.MAX_VALUE requests are send to Redis using RedisClient

SEVERE: Unhandled exception
java.lang.ArrayIndexOutOfBoundsException: -7483648
        at io.vertx.redis.client.impl.ArrayQueue.peek(ArrayQueue.java:72)
        at io.vertx.redis.client.impl.ArrayQueue.poll(ArrayQueue.java:83)
        at io.vertx.redis.client.impl.RedisClient.lambda$handle$14(RedisClient.java:348)

### Reproducer
```
public class ArrayQueueTest {
    @Test
    public void testOverflow() {
        ArrayQueue arrayQueue = new ArrayQueue(10);

        arrayQueue.offer(0);
        for (int i = 0; i < Integer.MAX_VALUE; i++) {
            arrayQueue.offer(0);
            arrayQueue.poll();
        }
        assertEquals(9, arrayQueue.freeSlots());
        assertEquals(0, (int) arrayQueue.poll());
        assertEquals(10, arrayQueue.freeSlots());
        //Overflow for int back
        arrayQueue.offer(1);
        //Overflow for int front
        assertEquals(1, (int) arrayQueue.poll());
    }
}
```

### bugfix

ArrayQueue.java lines 58 and 85:
(...)
back++;
if (back < 0) back = 0 - back % queue.length;
(...)

(...)
front++;
if (front < 0) front = 0 - front % queue.length;
(...)

**Comment by sagaxu** [comment]
```java
  <T> void offer(T value) {
    if (isFull()) {
      throw new IndexOutOfBoundsException();
    }
    back++;
    if (back == Integer.MAX_VALUE) {
      // ensure the indexes stay positive
      back = 0;
    }
    queue[back % queue.length] = value;
    cur++;
  }
```
write the value to queue[0] if back == Integer.MAX_VALUE, is it possible that queue[0] is used by another value?

e.g.
```java

#: values
_: empty slots
                     here
#####################_________________######
0                  back             front
```

one possible solution
```java
if (back == Integer.MAX_VALUE) {
    back %= queue.length;
}
```

**Comment by sagaxu** [comment]
the same change may be applied to the front too
