### ISSUE TITLE
No ability to set master password in Sentinel mode

### ISSUE THREAD

**Issue by mivanov1988** [vert-x3/vertx-redis-client#222]
### Version

* vert.x core:4.0.0-milestone4
* vert.x redis client:4.0.0-milestone4

### Context

Redis setup: 3 sentinels, 1 master and 2 slaves. The sentinels don't required an authentication, where the master does. There is no ability to set password for the master instance in Sentinel mode.

### Do you have a reproducer?

The application is using the following configuration:

RedisOptions redisOptions = new RedisOptions()
            .addConnectionString("redis://sentinel1:26379")
            .addConnectionString("redis://sentinel2:26379")
            .addConnectionString("redis://sentinel3:26379")
            .setRole(RedisRole.MASTER)
            .setMasterName("mymaster")
            .setType(RedisClientType.SENTINEL);

Redis client =  Redis.createClient(vertx,redisOptions);

### Extra

RedisSentinelClient.java:237

```
handler.handle(
            Future.succeededFuture("redis://" + response.get(0).toString() + ":" + response.get(1).toInteger()));
```

**Comment by pmlopes** [comment]
This one is tricky because we are receiving the node ip and port from the query and of course no password. So we will need to get the password from the provided connection strings. 

We will need to keep a reference to the connections config and look up by ip port.

**Comment by pmlopes** [comment]
This is fixed on master.
