### ISSUE TITLE
If connection to Redis server break, the send command promise will never complete on connection mode.

### ISSUE THREAD

**Issue by liukch** [vert-x3/vertx-redis-client#225]
### Version

vert.x core: 3.9.0
vert.x redis client: 3.9.0

### Context

I use connection mode, but when the connection to Redis is broke, the send command promise will never be completed.
I read the source code, I find in ```io.vertx.redis.client.impl.ArrayQueue```, there are three params: **front** / **back** / **cur**. If you always ```poll()```, the **front** always plus plus, but **back** never changed. When you ```poll()``` much more than ```offer()```, the **front** will much greater than **back**, the ```poll()``` will always return **null**. 
So in ```io.vertx.redis.client.impl.RedisConnectionImpl#cleanupQueue```, you can not fail any promise which in waiting queue.

### Steps to reproduce

1. Create ResidConnection, connect to Redis server
2. Send a lot of requests to Redis server with RedisConnection
3. Close Redis server
4. Request promise will not be completed in step 2.

**Comment by liukch** [comment]
@pmlopes Can you give me some advice about this problem?  Thanks a lot.

**Comment by pmlopes** [comment]
Can you try it with master? Some changes have been done to safeguard against wrong state on the queue.

**Comment by pmlopes** [comment]
Closing to inactivity and master may already solve the problem.
