### ISSUE TITLE
Redis client in 'pulled mode' miss commands

### ISSUE THREAD

**Issue by glassfox** [vert-x3/vertx-redis-client#229]
version: Redis Client 3.9.0

### Context

After upgrade to version 3.9.0 sometimes commands do not reach the redis server (without any exception).
This behavior is infrequent and occurs in 'pulled mode'. I lack to create test that reproduce the issue.
Yesterday I move my redis module to 'connection mode' and meanwhile the issue didn't occurs.

few points:
1. environment has mixed, 'pulled' and 'connection' modes. (not sure if this affect)
2. 'command miss' happened after massive amount of commands. (as next portion of commands)

**Comment by pmlopes** [comment]
@glassfox what do you mean by `pulled` mode?

**Comment by glassfox** [comment]
Hi @pmlopes, 
My mistake. I mean `pooled`.
Pooled mode - mean connection pool via Redis.send()
Lingo from code comments:

https://github.com/vert-x3/vertx-redis-client/blob/93f865453d18a15aa3ed54bd2191b975b0187480/src/main/java/io/vertx/redis/client/impl/RedisAPIImpl.java#L52-L58

**Comment by pmlopes** [comment]
Does large amount of commands is somehow close to Integer.MAX_VALUE?

There was an issue when the total run commands would reach that value and the overflow was not handled properly

**Comment by glassfox** [comment]
You mean total sent commands ? Maybe.
My config: "maxPoolWaiting" is 100000 and "maxPoolSize" is 8
I able to check this in my environment. 
Any log, metric or error handling able to help me to insure the overflow ?

**Comment by pmlopes** [comment]
The queue has been fixed to become circular (no overflows).
