### ISSUE TITLE
Reconnection fails completely

### ISSUE THREAD

**Issue by akoufa** [vert-x3/vertx-redis-client#232]
Hello to all. I am using the code from the example [Vertx Redis](https://vertx.io/docs/vertx-redis-client/java/#_implementing_reconnect_on_error) but it seems that the `exceptionHandler` is not working correctly. I am testing it locally by restarting Redis docker container but the Redis client does not reconnect again and the `exceptionHandler` is not called at all. I am using the Redis client in a Quarkus project where I am opening a connection in an `@ApplicationScoped` Bean that I am intending to inject in various places in the code to be able to cache and retrieve objects from Redis. 

Version:
Vertx 3.8.5 with Quarkus 1.4.1

**Comment by pendula95** [comment]
Can you please provide a small reproducer?

**Comment by akoufa** [comment]
@pendula95 I can try to find time to create a small reproducer. But the issue is happening just using the vertx redis client (version: 3.8.5) according to the documentation and then restarting the redis instance.

**Comment by pendula95** [comment]
I have created a small example that shows reconnect logic is working. Test wit standalone redis in docker. Vertx Redis Version 3.9.0. 
Start redis -> start vertx project -> wait for couple success calls -> stop redis -> get reconnect message -> start redis -> success output.
I am attaching a reproducer.
`class RedisVerticle extends AbstractVerticle {

    private static final int MAX_RECONNECT_RETRIES = 16;

    private RedisOptions options = new RedisOptions();
    private RedisConnection client;

    @Override
    public void start() {
        createRedisClient(onCreate -> {
            if (onCreate.succeeded()) {
                // connected to redis!
                System.out.println("Connected");

                vertx.setPeriodic(1000, id -> {
                    client.send(Request.cmd(Command.PING), result -> {
                        if (result.succeeded()) {
                            System.out.println("Working");
                        } else {
                            System.out.println("Error");
                        }
                    });
                });
            }
        });
    }

    /**
     * Will create a redis client and setup a reconnect handler when there is
     * an exception in the connection.
     */
    private void createRedisClient(Handler<AsyncResult<RedisConnection>> handler) {
        Redis.createClient(vertx, options)
                .connect(onConnect -> {
                    if (onConnect.succeeded()) {
                        client = onConnect.result();
                        // make sure the client is reconnected on error
                        client.exceptionHandler(e -> {
                            // attempt to reconnect
                            attemptReconnect(0);
                        });
                    }
                    // allow further processing
                    handler.handle(onConnect);
                });
    }

    /**
     * Attempt to reconnect up to MAX_RECONNECT_RETRIES
     */
    private void attemptReconnect(int retry) {
        System.out.println("Reconnecting " + retry);
        if (retry > MAX_RECONNECT_RETRIES) {
            // we should stop now, as there's nothing we can do.
            return;
        } else {
            // retry with backoff up to 10240 ms
            long backoff = (long) (Math.pow(2, Math.min(retry, 10)) * 10);

            vertx.setTimer(backoff, timer -> createRedisClient(onReconnect -> {
                if (onReconnect.failed()) {
                    attemptReconnect(retry + 1);
                }
            }));
        }
    }
}
![Screenshot_2020-07-22_13-42-37](https://user-images.githubusercontent.com/1239791/88172427-41e90a00-cc21-11ea-92b2-d3b39da415d7.png)
`

**Comment by akoufa** [comment]
@pendula95 Thank you for checking it. It seems then fixed with Vertx 3.9.0 . I will proceed with closing this ticket for the moment.

**Comment by geniusit** [comment]
Could you provide a code sample how to connect to a AWS ElasticCache Redis server with the IAM Module?
Here is some [documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html)
This [sample code](https://github.com/aws-samples/elasticache-iam-auth-demo-app/blob/main/src/main/java/com/amazon/elasticache/IAMAuthDemoApp.java) from AWS uses the Lettuce driver.
I m trying to accomplish it with low level vertx client as explained [in the quarkus documentation](https://quarkus.io/guides/redis-reference#apis)
I need to use with the [STSAssumeRoleSessionCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/STSAssumeRoleSessionCredentialsProvider.html)
Some [aws documentation](https://docs.aws.amazon.com/sdkref/latest/guide/feature-assume-role-credentials.html)

How to do ?

Thank you
