### ISSUE TITLE
wrong password with old api in 3.9

### ISSUE THREAD

**Issue by okou19900722** [vert-x3/vertx-redis-client#235]
In the old api, it will convert `io.vertx.redis.RedisOptions` to a connectionString like:

```
redis://localhost:6379/0?password=xxx
```

but if my password contains '#', it will get a wrong password in `RedisURI`, it seem like that the password dos not encode. e.g

```
redis://localhost:6379/0?password=abc#123
```
The real password is `abc#123`，but the param in the query is `abc`

**Comment by pmlopes** [comment]
Yes it should be URL encoded in the concatenation and URL decoded while parsing the value.

**Comment by gaol** [comment]
Agreed, according to https://tools.ietf.org/html/rfc3986#section-3.5, the `#` sign indicates the fragment part of the URI, you need to encode the password part using `java.net.URLEncoder.encode("abc#123")` to work :)

**Comment by okou19900722** [comment]
fixed in https://github.com/vert-x3/vertx-redis-client/pull/236
