### ISSUE TITLE
RedisConnection#Handler's handler never called

### ISSUE THREAD

**Issue by MYDIH** [vert-x3/vertx-redis-client#239]
### Version

4.0.0-milestone5

### Context

Trying to use Pub/Sub with no luck. No exception raised, the handler is just not called. May be linked to SSL ?!

### Steps to reproduce

1. Connect to a redis server using SSL
```
Redis.createClient(vertx, "rediss://:<password>@<host>:<port>")
                    .connect(onConnect -> {
                        if (onConnect.succeeded()) {
                            RedisConnection client = onConnect.result();

                            client.handler(message -> logger.info(Json.encode(message)))
                                .exceptionHandler(ex -> logger.error("Something went wrong while listening to redis Pub/Sub", ex));


                            client.send(Request.cmd(Command.PUBLISH).arg("channel1").arg("Hello World!"), res -> {
                                if (res.succeeded()) {
                                    logger.info("done");
                                } else logger.error("Can't publish a message to redis Pub/Sub", res.cause());
                            });
                        } else logger.error("Can't connect to redis cluster", onConnect.cause());
                    });
```

`done` is written to the console but the handler isn't called (no message logged nor called during a debug session). I also tried to send a message directly using the redis-cli tool, same result.

### Extra

* Java 11

**Comment by pmlopes** [comment]
@MYDIH The handler will only be called if you have `subscribed` to a channel or pattern, unless you do that the server will not echo back the messages. I don't know exactly how it works with `redis-cli` but I suspect that you just see the echo of the command you wrote.

If you subscribe first to the `channel1` and then publish you should be able to see it.

**Comment by MYDIH** [comment]
Can I ask you an example ? Or maybe you could point me to the right documentation, it seems I can't find it on my own ...
