### ISSUE TITLE
RedisAPI redis is abnormal when the network is disconnected

### ISSUE THREAD

**Issue by wbkys** [vert-x3/vertx-redis-client#240]
### Questions

RedisAPI redis is abnormal when the network is disconnected.
 
I know he was caused by a network disconnect,
But this exception cannot be caught because it cannot be reconnected.

For example:
RedisAPI redis.redis == null

### Version

vertx-redis-client 3.9.1

### Context

八月 03, 2020 2:49:59 下午 io.vertx.redis.client.impl.ConnectionManager
严重: Unhandled Error
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:124)
	at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:205)
	at io.vertx.core.net.impl.NetSocketImpl.writeMessage(NetSocketImpl.java:130)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:174)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:168)
	at io.vertx.redis.client.impl.RedisConnectionImpl.lambda$send$1(RedisConnectionImpl.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)

* Link to github project/gist

### Steps to reproduce

1. ...Start client
2. ...Disconnection

### Extra

* Anything that can be relevant such as OS version, JVM version
JDK 1.8

**Comment by pendula95** [comment]
Can you please provide a small example as I can not reproduce this

**Comment by wbkys** [comment]
`package com.audio.starter;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;
import io.vertx.redis.client.Redis;
import io.vertx.redis.client.RedisAPI;
import io.vertx.redis.client.RedisClientType;
import io.vertx.redis.client.RedisOptions;

public class TestRedis extends AbstractVerticle{
	private RedisOptions options;
	private RedisAPI redis;
	
	@Override
	public void start(Promise<Void> startFuture)  {
		
		options = new RedisOptions().setType(RedisClientType.STANDALONE).addConnectionString("redis://:test@127.0.0.1:6379/1");
		
		vertx.setPeriodic(10000, id -> {
			ping();
		});
		
		Redis.createClient(vertx, options).connect(onConnect -> {
			if (onConnect.succeeded()) {
				redis = RedisAPI.api(onConnect.result());
				startFuture.complete();
			} else {
			}
		});
	}
	
	/**
	 * ping
	 */
	private void ping() {
		redis.echo("ping", handler -> {
			System.out.println(handler.result());
		});
	}
	
}
`

Deploy TestRedis.class ,  Then disconnect the network. 
An error occurs. After the network is restored, no way attemptReconnect

**Comment by pendula95** [comment]
Please read this, as this covers the issue you have. You need to implement exception handler that should perform reconnect for you. https://vertx.io/docs/vertx-redis-client/java/#_implementing_reconnect_on_error

Also here is a small snippet for your case that I have tested:
```
import io.vertx.core.AbstractVerticle;
import io.vertx.core.AsyncResult;
import io.vertx.core.Handler;
import io.vertx.core.Promise;
import io.vertx.redis.client.*;

import java.nio.channels.ClosedChannelException;

public class RedisVerticle extends AbstractVerticle {

    private static final int MAX_RECONNECT_RETRIES = 16;

    private RedisOptions options;
    private RedisConnection redis;

    @Override
    public void start(Promise<Void> startFuture) {

        options = new RedisOptions().setType(RedisClientType.STANDALONE).addConnectionString("redis://:test@127.0.0.1:6379/1");

        createRedisClient(onCreate -> {
            if (onCreate.succeeded()) {
                System.out.println("Connected");
                startFuture.complete();

                vertx.setPeriodic(1000, id -> {
                    ping();
                });
            } else {
                onCreate.cause().printStackTrace();
            }
        });
    }

    /**
     * ping
     */
    private void ping() {
        redis.send(Request.cmd(Command.PING), handler -> {
            if(handler.succeeded()) {
                System.out.println(handler.result());
            } else {
                handler.cause().printStackTrace();
            }
        });
    }

    /**
     * Will create a redis client and setup a reconnect handler when there is
     * an exception in the connection.
     */
    private void createRedisClient(Handler<AsyncResult<RedisConnection>> handler) {
        Redis.createClient(vertx, options)
                .connect(onConnect -> {
                    if (onConnect.succeeded()) {
                        redis = onConnect.result();
                        // make sure the client is reconnected on error
                        redis.exceptionHandler(e -> {
                            // attempt to reconnect
                            if(e instanceof ClosedChannelException) {
                                System.out.println("Trying to reconnect");
                                attemptReconnect(0);
                            } else {
                                System.out.println("Fatal error will not try anything, error = " + e.getMessage());
                            }
                        });
                    }
                    // allow further processing
                    handler.handle(onConnect);
                });
    }

    private void attemptReconnect(int retry) {
        if (retry > MAX_RECONNECT_RETRIES) {
            // we should stop now, as there's nothing we can do.
        } else {
            // retry with backoff up to 10240 ms
            long backoff = (long) (Math.pow(2, Math.min(retry, 10)) * 10);

            vertx.setTimer(backoff, timer -> createRedisClient(onReconnect -> {
                if (onReconnect.failed()) {
                    attemptReconnect(retry + 1);
                }
            }));
        }
    }
}
```

@pmlopes I think you should remove bug from this issue.

**Comment by pmlopes** [comment]
Also note that we now also have a connection pool. In this case you don't need to get a connection anymore (explicitly) and it manages the reconnect for you (on error, or ttl the connection expires, the socket is closed and a new one is open for you)

**Comment by wbkys** [comment]
I'm sorry, I've ignored this

**Comment by wbkys** [comment]
use  https://vertx.io/docs/vertx-redis-client/java/#_implementing_reconnect_on_error 
If you disconnect the network twice, an unrecoverable exception will appear

**Comment by wbkys** [comment]
I'm too stupid

 attemptReconnect add client.exceptionHandler(e -> {
			            this.attemptReconnect(1);
			        });
