### ISSUE TITLE
How to support protobuff serialization

### ISSUE THREAD

**Issue by lygoing** [vert-x3/vertx-redis-client#250]
Hi.

The RedisAPI operation method parameters are all String. What should I do with my binary value?  
Do I need to use base64? oh no. 😂

Best Regards.

**Comment by lygoing** [comment]
I seem to have found it, I may not be able to use RedisAPI.

```
client.send(Request.cmd(Command.SET).arg("testBuffer").arg(Buffer.buffer("testBuffer".getBytes())));
```

Any suggestions? I don't know anything about redis. 


thanks.

**Comment by pmlopes** [comment]
If you pass arguments as `Buffer` they are considered to be binary. Indeed the `RedisAPI` helper only works with Strings for now.

**Comment by lygoing** [comment]
@pmlopes  Thank you very much. ☕
