### ISSUE TITLE
Unexpected Thread switch after Redis command execution

### ISSUE THREAD

**Issue by annashumylo** [vert-x3/vertx-redis-client#256]
Hello all, 
I'm using vertx-redis-client latest version(4.0.0-milestone5) and I detected a weird behavior.
When some calls from different threads are executed to Redis using connection pool, the current thread always became the same (same id) after receiving the result.

The same behavior was In the past for PgPoo. But we saw a fix in vertx4, so I'm surprised that same issue exists now in the new Redis pool..

Way to reproduce:

Redis initialization:
```
RedisOptions options = new RedisOptions().setConnectionString("redis://localhost:6379").setMaxPoolSize(10);
Redis redis = Redis.createClient(vertx, options);
```

HttpServer with routing and current thread detection:
```
router.get("/test_redis").handler(routingContext -> rootingRedisTest(routingContext, currentThread));
```

rootingRedisTest:
```
private void rootingRedisTest(RoutingContext routingContext, String currentThread) {
		try {
			Thread.sleep(500);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		redisAPI.rxInfo(Collections.emptyList()).flatMapCompletable(result -> {
			System.out.println("RedisApi instance: " + redisAPI.toString());
			System.out.println(
					"Thread after Redis call executing: " + Thread.currentThread().getName() + ". Initial thread: "
							+ currentThread);
			return Completable.complete();
		}).subscribe(() -> {
			HttpServerResponse response = routingContext.response();
			response
					.putHeader("content-type", "text/html").setStatusCode(200)
					.end("Server is healthy");
		}, error -> {
			System.out.println(error);
			HttpServerResponse response = routingContext.response();
			response
					.putHeader("content-type", "text/html").setStatusCode(500)
					.end("Server error: ", error.getMessage());
		});
	}
```
Test:
```
@Test
	void redis_test(VertxTestContext testContext) throws Throwable {
		for (int i = 0; i < 10; i++) {
			sendGetRequest("test_redis");
		}
		testContext.completeNow();
	}
```
Test execution result:
![image](https://user-images.githubusercontent.com/72810335/95882629-39185800-0d7a-11eb-86ae-bc4c58a24028.png)

**Comment by pmlopes** [comment]
The latest version is io.vertx:vertx-redis-client:4.0.0.Beta3

Milestone 5 is from May 2020 and many updates have been added.

Can you verify it?

**Comment by annashumylo** [comment]
> The latest version is io.vertx:vertx-redis-client:4.0.0.Beta3
> 
> Milestone 5 is from May 2020 and many updates have been added.
> 
> Can you verify it?

Sorry, you are right. But unfortunately with Beta3 thread problem still remain.

**Comment by pmlopes** [comment]
Hi, could you give a shot if PR #259 fixes this? It still needs to handle the promise based api + tests

**Comment by annashumylo** [comment]
> Hi, could you give a shot if PR #259 fixes this? It still needs to handle the promise based api + tests

Hey, I tried to test it with 4.0.0-SNAPSHOT version and for vertx-redis-client I used a jar file from https://github.com/vert-x3/vertx-redis-client/tree/issues/256 but it still doesn't work.

**Comment by pmlopes** [comment]
Hi @annashumylo could you help out preparing a unit test that reproduces the issue and fails it? I'm ooo this week but it would help me try to triage where the switch is going wrong.

**Comment by annashumylo** [comment]
Hi, @pmlopes , no problem. You can use this:
```
	@Test
	void redisThreadConsistencyTest(VertxTestContext testContext) {
		Vertx vertx = Vertx.vertx();
	    deployVerticle(vertx, testContext);

		HttpRequest<String> request = WebClient
				.create(vertx)
				.get(8080, "localhost", "/")
				.as(BodyCodec.string());

		request.rxSend().subscribe(response -> testContext.verify(() -> {
							Assertions.assertEquals(response.getHeader("initialThread"), response.getHeader("threadAfterRedisExecution"));
							testContext.completeNow();
						}), testContext::failNow);
	}

	void deployVerticle(Vertx vertx, VertxTestContext testContext) {
		RedisAPI redisAPI = RedisAPI.api(Redis.createClient(vertx));
		RxHelper.deployVerticle(vertx, new Verticle(redisAPI))
				.subscribe(id -> testContext.completing(), testContext::failNow);
	}

	static class Verticle extends AbstractVerticle {

		RedisAPI redisAPI;

		Verticle(RedisAPI redisApi) {
			this.redisAPI = redisApi;
		}

		@Override
		public void start(Promise<Void> startFuture) {
			vertx.createHttpServer()
					.requestHandler(req -> {
						String threadBeforeRedisCommandExecution = Thread.currentThread().getName();
						redisAPI.info(Collections.emptyList(), result -> {
							String threadAfterRedisCommandExecution = Thread.currentThread().getName();
							req.response().putHeader("initialThread", threadBeforeRedisCommandExecution)
									.putHeader("threadAfterRedisExecution", threadAfterRedisCommandExecution)
									.end("Ok");
						});
					})
					.rxListen(8080)
					.subscribe(server -> startFuture.complete(), startFuture::fail);
		}
	}
```

**Comment by pmlopes** [comment]
@annashumylo I've completed the "refactor" to ensure we're on the right thread.

https://github.com/vert-x3/vertx-redis-client/pull/259

I've added your test (with some small changes to avoid pulling dependencies). I have the feeling that now we're doing the things right (and the test is green on my side too).

As it's a bit of a refactor, could you run some tests on your side on that specific pull request / branch? If you don't encounter any issue, let me know and I'll merge! :crossed_fingers:

**Comment by annashumylo** [comment]
@pmlopes hi, works on my side too! Thank you for a such a nice job :)
