### ISSUE TITLE
Cluster client is only authenticating initial connection

### ISSUE THREAD

**Issue by pyranja** [vert-x3/vertx-redis-client#270]
### Version

3.9.4

### Context

We are upgrading to vertx 3.9.4 and ported to the new redis client implementation.

Connecting to an insecure cluster works, but requests to an authenticated cluster fail with:

`NOAUTH Authentication required.`

When inspecting the netty logs, it's apparent that only the first connection sends a `AUTH` command using the configured password. That connection is used to get cluster/slots information and is dropped afterwards.
The cluster client then establishes connections to each discovered cluster member, but does **not** send an `AUTH` command after connecting.

I think the reason is, that after determining all available slots, the cluster client connects using the endpoints from the `SLOTS` response, which do not include the password.

A fix could be to patch derived endpoints, if the initial connection string included a password.

### Do you have a reproducer?

Enable log activity on the net client and connect to a redis cluster that required authentication, for example ElastiCache.

### Steps to reproduce

see above

### Extra

* n/a

**Comment by pyranja** [comment]
I might be able to provide a PR if, my fix idea works.

Can you think of a different workaround @pmlopes ?

**Comment by pmlopes** [comment]
@pyranja I think this issue is solved in master (currently 4.0.0) using the same idea. Please feel free to have a look at the master code and certainly, do a pull request :+1:

**Comment by pmlopes** [comment]
Should be in 3.9.5
