### ISSUE TITLE
In sentinel mod, sentinel connection has been subscribed but not unsubscribe when close

### ISSUE THREAD

**Issue by lyt2012** [vert-x3/vertx-redis-client#281]
### Version

Vertx-redis-client: 4.0.2

### Context

In SENTINEL mod, second reuse the sentinel connection but failed
![image](https://user-images.githubusercontent.com/25401139/109094704-624bea80-7755-11eb-83d2-83200e579a27.png)

Actual exception
![image](https://user-images.githubusercontent.com/25401139/109094815-92938900-7755-11eb-93e6-453d0af9a8d4.png)

### Extra

RedisSentinelClient.connect()
![image](https://user-images.githubusercontent.com/25401139/109094998-e30ae680-7755-11eb-91f5-36207f6863b6.png)
![image](https://user-images.githubusercontent.com/25401139/109095013-e9995e00-7755-11eb-819d-bf4e69e3563c.png)
![image](https://user-images.githubusercontent.com/25401139/109095412-a1c70680-7756-11eb-9b24-2cdab8f5d151.png)
![image](https://user-images.githubusercontent.com/25401139/109095457-bb684e00-7756-11eb-9cac-43c3565c8233.png)

**Comment by lyt2012** [comment]
![image](https://user-images.githubusercontent.com/25401139/109096243-29614500-7758-11eb-8a3b-3581429826a1.png)
It's my solution

**Comment by lyt2012** [comment]
![image](https://user-images.githubusercontent.com/25401139/109097177-cffa1580-7759-11eb-9883-f90eac9bb710.png)
It's my options

**Comment by pmlopes** [comment]
@lyt2012 would you like to make a pull request and add a test for this?

**Comment by lyt2012** [comment]
@pmlopes ok, i'd like do this

**Comment by lyt2012** [comment]
@pmlopes 
1. Hello, i fork the newest repository 4.0.4-snapshot, and i found the bug has been fixed. 
2. The newest master code, creating a new connection each time, it looks like the connection pool is not working normally.
3. I could't sure if this is a bug, the implementation is a little bit complicated for me, please see the screenshots below.
4. My pool's max size is 2, but every time a connection is created, and the pool's avaliable parameter forever been empty.
`public class RedisTest {

	static AtomicInteger count = new AtomicInteger(1);
	
	public static void main(String[] args) {
		Vertx vertx = Vertx.vertx(new VertxOptions().setBlockedThreadCheckIntervalUnit(TimeUnit.DAYS));
		RedisOptions options = 
				new RedisOptions()
					.setType(RedisClientType.SENTINEL)
					.addConnectionString("redis://127.0.0.1:26379")
					.setRole(RedisRole.MASTER)
					.setMaxPoolSize(2);
		RedisSentinelClient client = (RedisSentinelClient) Redis.createClient(vertx, options);

		vertx
			.createHttpServer()
			.requestHandler(req -> test(client, req))
			.listen(8080, ar -> {
				if (ar.succeeded()) {
					System.out.println("Server started");
				}
				else {
					ar.cause().printStackTrace();
				}
			});
	}
	
	private static void test(RedisSentinelClient client, HttpServerRequest request) {
		client.connect(ar -> {
			if (ar.succeeded()) {
				RedisConnection connection = ar.result();
				System.out.println(count.getAndIncrement() + ": get a connection");
				
				connection.close();
			}
			else {
				System.out.println(count.getAndIncrement() + ": exception with ");
				ar.cause().printStackTrace();
			}
			request.response().end("ok");
		});
	}
	
}`
![image](https://user-images.githubusercontent.com/25401139/111023275-03ec6080-8413-11eb-8e78-02f7308a2d84.png)
![image](https://user-images.githubusercontent.com/25401139/111023286-0f3f8c00-8413-11eb-87c9-63093f8179c7.png)

**Comment by lyt2012** [comment]
@pmlopes 
1. Hello, i fork the newest repository 4.0.4-snapshot, and i found the bug has been fixed.
2. The newest master code, creating a new connection each time, it looks like the connection pool is not working normally.
3. I could't sure if this is a bug, the implementation is a little bit complicated for me, please see the screenshots below.
4. My pool's max size is 2, but every time a connection is created, and the pool's avaliable parameter forever been empty.

![image](https://user-images.githubusercontent.com/25401139/111023433-fc798700-8413-11eb-8be7-341bb8eec452.png)
![image](https://user-images.githubusercontent.com/25401139/111023434-000d0e00-8414-11eb-9237-240e1b708f8f.png)

` 
  public class RedisTest {
  
	  static AtomicInteger count = new AtomicInteger(1);
	  
	  public static void main(String[] args) {
		  Vertx vertx = Vertx.vertx(new VertxOptions().setBlockedThreadCheckIntervalUnit(TimeUnit.DAYS));
		  RedisOptions options = 
				  new RedisOptions()
					  .setType(RedisClientType.SENTINEL)
					  .addConnectionString("redis://127.0.0.1:26379")
					  .setRole(RedisRole.MASTER)
					  .setMaxPoolSize(2);
		  RedisSentinelClient client = (RedisSentinelClient) Redis.createClient(vertx, options);
  
		  vertx
			  .createHttpServer()
			  .requestHandler(req -> test(client, req))
			  .listen(8080, ar -> {
				  if (ar.succeeded()) {
					  System.out.println("Server started");
				  }
				  else {
					  ar.cause().printStackTrace();
				  }
			  });
	  }
	  
	  private static void test(RedisSentinelClient client, HttpServerRequest request) {
		  client.connect(ar -> {
			  if (ar.succeeded()) {
				  RedisConnection connection = ar.result();
				  System.out.println(count.getAndIncrement() + ": get a connection");
				  
				  connection.close();
			  }
			  else {
				  System.out.println(count.getAndIncrement() + ": exception with ");
				  ar.cause().printStackTrace();
			  }
			  request.response().end("ok");
		  });
	  }
	  
  } 
`

**Comment by lyt2012** [comment]
@pmlopes 
In short, it seems that the connection is not reused and a new connection is created every time, so there is no need to unsubscribe.

**Comment by pmlopes** [comment]
The pool takes 2 config values, max size and max waiting. Max waiting are the number of get connections calls that are queued until a connection is available. You should set the 2 or you may be watching queuing. 

If max waiting is negative then the waiting is unbounded

**Comment by lyt2012** [comment]
@pmlopes 
ok, i'll close this issue first, because the bug can't be reproduced in the newest code
