### ISSUE TITLE
Usage of poolRecycleTimeout

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-redis-client#290]
The `RedisOptions` define `poolRecycleTimeout` that is currently un-used.

It is not clear what this setting does and if that is related to the idle timeout (that is not implemented yet see https://github.com/vert-x3/vertx-redis-client/issues/289).

I believe this option should be deprecated and removed later unless we have a case for it.

**Comment by akshaypatidar-d11** [comment]
In vertx `3.9.x` when we close a connection it was closed after `poolRecycleTimeout` period (`close` method in `RedisConnectionImpl.java`)
Is this removed in this vertx 4?
