### ISSUE TITLE
Handle Subscribe/Unsubscribe response messages

### ISSUE THREAD

**Issue by cristian-com** [vert-x3/vertx-redis-client#291]
## Describe the feature
Other kind of messages apart from "message" are not being handled by default. Currently only "messages" are being sent as Json objects to the even bus, for others a warning message is being printed. e.g: WARNING: No handler waiting for message: [subscribe, channel, 1]

Unless this is the expected behaviour I think all kind of messages should be handled in the same way.

All kind of responses are described [here](https://redis.io/topics/pubsub)

> Format of pushed messages
> A message is a Array reply with three elements.
> 
> The first element is the kind of message:
> 
> subscribe: means that we successfully subscribed to the channel given as the second element in the reply. The third argument represents the number of channels we are currently subscribed to.
> 
> unsubscribe: means that we successfully unsubscribed from the channel given as second element in the reply. The third argument represents the number of channels we are currently subscribed to. When the last argument is zero, we are no longer subscribed to any channel, and the client can issue any kind of Redis command as we are outside the Pub/Sub state.
> 
> message: it is a message received as result of a PUBLISH command issued by another client. The second element is the name of the originating channel, and the third argument is the actual message payload.

#### Use cases

A list of use cases this feature will enable and the value it creates.

#### Contribution

I would be happy to add a pr, please check this commit: https://github.com/cristian-com/vertx-redis-client/commit/47a5b1a1392c1177a0412d6ef91dbe2e159bae77

If you consider the above applies I will make it look nicer in a private method and handle the missing cases for unsubscribe responses .

This issue was originally mentioned at: https://github.com/quarkusio/quarkus/issues/13887#issuecomment-746941729

**Comment by joana-pestana** [comment]
Any updates on this issue?
I'm encountering the same problem with version 4.5.7.
I came across this [PR](https://github.com/cristian-com/vertx-redis-client/commit/47a5b1a1392c1177a0412d6ef91dbe2e159bae77), but it seems quite old.

**Comment by Ladicek** [comment]
I'll do this on the `master` branch. Actually not exactly this -- I will extract the code that takes susbscription messages and sends them to the event bus into a separate class that implements `Handler<Response`>. Whoever wants that behavior will have to install that handler on the connection using `RedisConnection.handler()`.
