### ISSUE TITLE
redis connect string can't support password contains '@'

### ISSUE THREAD

**Issue by YuyuZha0** [vert-x3/vertx-redis-client#294]
### Questions

`redis://[:password@]host[:port][/db-number]`
As described, How can I escape '@' character in password, or had some alternatives?

**Comment by pmlopes** [comment]
@YuyuZha0 the connection string is a `URL` the correct way to encode `@` is to percent encode it: `%40` for example as in the test:

```
RedisURI redisURI = new RedisURI("redis://:p%40ssw0rd@redis-1234.hosted.com:1234/0");
assertEquals("p@ssw0rd", redisURI.password());
```
