### ISSUE TITLE
Add support for Redis ZUNION command

### ISSUE THREAD

**Issue by patrox** [vert-x3/vertx-redis-client#299]
[`ZUNION`](https://redis.io/commands/zunion) command is not supported - as at the moment only a similar [`ZUNIONSTORE`](https://redis.io/commands/zunionstore) command is supported.

ZUNION Redis command should follow the same logic as ZUNIONSTORE, but the only difference is that it won't store the resulting set, but it will be returned to the client. Given this similarity between these two commands, there is a nice opportunity to reuse some of the code, to avoid repetition.

#### Use cases

The main driver for this change is a feature request coming from Quarkus: https://github.com/quarkusio/quarkus/issues/18351, where `vertx-redis-client` is used as a dependency.

#### Contribution

I can work on addressing this issue by providing a PR with the changes to support this functionality.

**Comment by pmlopes** [comment]
@patrox we have some tooling for this, start a modern redis server 6.2.0 seems to be the case for this command. and run the js script in `tools`:

```
cd tools
npm i
npm start
```

It should create the command helpers java classes from the running server.

**Comment by pmlopes** [comment]
In the meantime you can still use the direct `send()` command by crafting the missing command manually.

**Comment by patrox** [comment]
Thank you @pmlopes, as this is what I was about to ask, since I saw a lot of comments about auto-generated code.

I'll give it a try, and will come back with the results.

**Comment by patrox** [comment]
> In the meantime you can still use the direct `send()` command by crafting the missing command manually.

Yep, this is a short term plan

**Comment by pmlopes** [comment]
Fixed with: https://github.com/vert-x3/vertx-redis-client/commit/8d783078dbcf369d2a58197925bbf31c4a2594e3

**Comment by machi1990** [comment]
@pmlopes thanks for the fix. Do you have a rough timeline of when we'll have a new release?

/cc @patrox
