### ISSUE TITLE
Unable to connect to redis/elasticache clusters over a certain size. Potential timeout issue?

### ISSUE THREAD

**Issue by brusic** [vert-x3/vertx-redis-client#310]
Using version 4.1.4 in a Spring/kotlin context using AWS Elasticache in clustered mode with redis 6.x.

The client has been working fine for us until we started upgrading cluster with larger sizes. No issues with clusters with 18 or under total shards (6 shards and 2 replicas), but fails to connect with anything over 7 shards. Same instance type (r5.4xlarge), subnet, security groups. The RedisClusterClient will fail with  "Cannot connect to any of the provided endpoints". 

I have a feeling it might be due to a timeout since the cluster client will sequentially connect to each endpoint, but I have not been able to verify this theory. All failures occur about 550 ms after a connection is attempted. However, connecting to clusters with 6x3 shards, also complete in the same amount of time or longer. Connection to clusters with 5x2 shards occurs in 100ms. Upped the max pool size to large values such as 200, just to remove it as a source of error.

Is there a timeout associated with establishing a connection to all shard nodes?

At wits end since there are no logs for the actual connection errors. Been testing with new clusters containing no data. Slots are the default ones. Debugging locally will return the correct number of master endpoints, but cannot progress further since the code cannot connect to the nodes outside of the VPC.

Example options:
```
{
"endpoint": "redis://....cache.amazonaws.com:6379",
"endpoints": [
"redis://....cache.amazonaws.com:6379"
],
"masterName": "mymaster",
"maxNestedArrays": 32,
"maxPoolSize": 96,
"maxPoolWaiting": 96,
"maxWaitingHandlers": 2048,
"netClientOptions": {
"logActivity": false,
"receiveBufferSize": -1,
"reuseAddress": true,
"reusePort": false,
"sendBufferSize": -1,
"trafficClass": -1,
"crlPaths": [],
"crlValues": [],
"enabledCipherSuites": [],
"enabledSecureTransportProtocols": [
"TLSv1",
"TLSv1.1",
"TLSv1.2"
],
"idleTimeout": 0,
"idleTimeoutUnit": "SECONDS",
"soLinger": -1,
"ssl": false,
"sslHandshakeTimeout": 10,
"sslHandshakeTimeoutUnit": "SECONDS",
"tcpCork": false,
"tcpFastOpen": false,
"tcpKeepAlive": true,
"tcpNoDelay": true,
"tcpQuickAck": true,
"useAlpn": false,
"connectTimeout": 100,
"metricsName": "redis",
"trustAll": false
},
"poolCleanerInterval": -1,
"poolRecycleTimeout": 15000,
"role": "MASTER",
"type": "CLUSTER",
"useReplicas": "ALWAYS"
}

```

**Comment by brusic** [comment]
Recently upgraded to 4.2.3 to see if the additional logging added in 4.2 would help us debug the issue. Did not see any new logging statements, but that could be our logging config. However, same issues. Have not dived deeper into the errors after the upgrade.

**Comment by pmlopes** [comment]
@brusic for 4.3 one of the goals is to make the redis client in cluster and sentinel modes, lazy. This means that the client will not attempt to connect to all nodes at start before starting executing commands. This approach works when the conditions are good, for example, small cluster size, no nodes down, no network errors.

This will require internal rewrites, but the public API shall remain almost untouched, a few methods that returned `void` shall need to return a `Future` to signal asynchronous operation results.

We're about to branch for 4.3, so meanwhile, if you could gather details on the cluster you're facing problems, so we could try to recreate it using test-containers as a test bed, that would be extremely helpful.

**Comment by brusic** [comment]
Turns out I was both correct and an idiot. In the end, it truly was a timeout issue, but that what `NetClientOptions().setConnectTimeout()` is for. Updated increased values were being ignored, so still had old values.

Connecting to an 18 node cluster works with a connection timeout of 100ms, but not a node of 21. The results were consistent, always succeeded with 18 node clusters, always failed with 21.

**Comment by hiteshbal91dp** [comment]
I have created docker redis-cluster with static IP mapping, when I tried from my host machine using redis-cli to any of the redis nodes. I am able to connect to the service. But my java code running with vertx-redis is not able to connect with redis-cluster. I am getting the following error 
"Cannot connect to any of the provided endpoints", Can you guys help me with what am I doing wrong here?
