### ISSUE TITLE
Username is not passed to AUTH command when Username is present in the URI connection

### ISSUE THREAD

**Issue by gutmox** [vert-x3/vertx-redis-client#315]
### Version

3.9.10 / 3.9 branch

### Context

In case Redis has username and password, when connecting with other than the default user, ConnectionManager is not passing username to the Auth Redis Command here:

https://github.com/vert-x3/vertx-redis-client/blob/dc2147d76ae3078ae9687ec4789029eac632fee9/src/main/java/io/vertx/redis/client/impl/ConnectionManager.java#L126

**Comment by craig-day** [comment]
I think this can be closed as fixed by #316? cc @pmlopes @vietj
