### ISSUE TITLE
Automatically refresh connections to redis cluster on shard/replica addition/deletion

### ISSUE THREAD

**Issue by akshaypatidar1999** [vert-x3/vertx-redis-client#320]
#### Describe the feature

**Refresh connections to redis cluster whenever there is a change in cluster**

Current redis client implementation creates connections to redis cluster and uses them to send requests to redis cluster. However if redis cluster is changed (new shards/replicas are added/deleted) then it does not automatically refreshes the connection, due to which we see errors like `MOVED 7652 10.0.4.210:6379` and we have to redeploy our service.

If we could somehow detect changes in the cluster and refresh connections then we can get rid of deploying whenver we scale/downscale redis cluster

One simple solution I can think of is to save the cluster information when connecting to cluster for the first time using `CLUSTER INFO/CLUSTER SLOTS` command. Then periodically run this command and if there is any change in the cluster we can refresh the connections.

#### Use cases

- In today's world we upscale/downscale our data stores on the fly so it becomes cumbersome to redeploy micro-services after each scaling activity. This feature will remove the need to redeploy micro-services when scaling a redis cluster

#### Contribution

I am willing to contribute to this feature.

**Comment by pmlopes** [comment]
Hi @akshaypatidar1999 thanks for your issue. This is indeed a highly requested feature. We can break the task into 2 areas:

* have the cluster discovery code run as a *"singleton"* per redis client instance
* close the client should become an asynchronous call to ensure that any discovery task is close properly

The same, similar logic should also apply to **sentinel** mode.

This also means that the static factories `createClient() : Redis` should become asynchronous too, as we may need to perform discovery for `cluster/sentinel`.

So, we either deprecate the old blocking API or leave it with a warning on the javadoc that that mode will only work for single node or replication mode.

**Comment by akshaypatidar1999** [comment]
Is there any plan to pick this feature?
I am willing to contribute to this feature.

**Comment by akshaypatidar1999** [comment]
@pmlopes @vietj I will happy to contribute to this feature

**Comment by ivivanov-bg** [comment]
@akshaypatidar1999 
If you have any ideas - I guess you can fork the repo and create a PR
