### ISSUE TITLE
RedisClusterClient does not handle command command, use non cluster client on the right node

### ISSUE THREAD

**Issue by hiteshbal91dp** [vert-x3/vertx-redis-client#340]
### Questions

We are using the 4.0.0 version of the vertx-redis-client and when we hit "INFO CLUSTER" command to our AWS elasticcache cluster it is throwing error "RedisClusterClient does not handle command command, use non cluster client on the right node" but if we connect from terminal to AWS ElasticCache it is working fine

Which version(s) did you encounter this bug ?
### Steps to reproduce

1. Connect to redis cluster specifying mentioned configs
2. After redis connection run the "INFO CLUSTER" command

### Extra

* We are using java 8 on macos m1 chipset.

**Comment by otoniel-zappyride** [comment]
The same occurs using Quarkus Health Check.

**Comment by pendula95** [comment]
This has been addressed, please use latest version 4.3.2 to avoid this issue. f43502bcf1e63566fc304a3d3f3349329989c2d1
