### ISSUE TITLE
PooledRedisConnection.close() does not close the connection if it is tainted (Pub/Sub)

### ISSUE THREAD

**Issue by Eng-Fouad** [vert-x3/vertx-redis-client#353]
On closing tainted connections, they are evicted from the connection pool without being closed which causes connection leaks.

**PooledRedisConnection#close()** -> **connection.reset()**:
https://github.com/vert-x3/vertx-redis-client/blob/741f219b1164e36558ff9f0abaa4044b0d1217c9/src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java#L82-L91

**RedisStandaloneConnection.reset()** -> **evict()**:
https://github.com/vert-x3/vertx-redis-client/blob/741f219b1164e36558ff9f0abaa4044b0d1217c9/src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java#L456-L468

**RedisStandaloneConnection.evict()**:
https://github.com/vert-x3/vertx-redis-client/blob/741f219b1164e36558ff9f0abaa4044b0d1217c9/src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java#L470-L479

`netSocket.close()` is missing.

Affected version: 4.3.4

**Comment by Eng-Fouad** [comment]
@pmlopes @cescoffier when will 4.3.5 be released? Hopefully we can integrate it with the next release (2.14.0) of Quarkus.

**Comment by pmlopes** [comment]
From the vertx side this is merged on master, so it shall be present on the next release 4.3.5.
