### ISSUE TITLE
redis client shared in multiple verticles in high concurrency load will make redis call get response belonged to another request with some specific keys

### ISSUE THREAD

**Issue by LangInteger** [vert-x3/vertx-redis-client#394]
### Questions

In my case, the Redis call seems to get a response that does not relate to the request but belonged to another request.

### Version

I'm writing a test case based on the redis-client newest commit 62c209b based on the master branch

### Context

Here is the test code: https://github.com/LangInteger/vertx-redis-client/blob/20230701_lang_test_shared_redis_connection/src/test/java/io/vertx/redis/RedisTestVerticle.java

Docker is needed to run the code.

### Steps to reproduce

1. clone the repo
2. open RedisTestVerticle
3. start the main function
4. you can see some Redis call success with some fail (in a weird way)

![image](https://github.com/vert-x3/vertx-redis-client/assets/17768055/941586d4-65ad-422d-b01d-b1b91ba2f050)

### Extra

Something I want to make a note:

- the redis key matters
  - I tested with another key pair `number_key` and `set_key`, and there will be no errors

    ```java
      private static final String REDIS_NUMBER_VALUE_KEY = "number_key";
      private static final String REDIS_SET_VALUE_KEY = "set_key";
    ```

- the number of verticles matters
  - I tested with verticle instance 1, and there will be no errors
  
    ```java
            vertx.deployVerticle(RedisTestVerticle.class,
              new DeploymentOptions().setInstances(1));
    ```

- the request load matters
  - I tested with for loop 10, and there will be no errors
  
    ```java
      public static void loopTest() {
        for (int i = 0; i < 10; i++) {
          System.out.println(Thread.currentThread() + "execute loop: " + i);
          test1();
        }
      }
    ```

**Comment by Ladicek** [comment]
I've inspected the reproducer carefully and also played with it locally, and I believe it doesn't use the Vert.x Redis client API correctly. Specifically, it shares a _single connection_ between multiple verticles. That single connection is written to concurrently, with zero coordination.

Instead, what should be shared is the Redis _client_. This means that connections are not shared, which means that they are not used concurrently, which means there's no overlap between requests and responses. Executing commands through the client uses connection pooling under the hood, so the actual number of TCP connections is limited.

In terms of code, this method

```java
private static Future<Void> connectToRedisCluster(Vertx vertx) {
  return Redis.createClient(vertx, options)
    .connect()
    .compose(conn -> {
      redisAPI = RedisAPI.api(conn);
      return Future.succeededFuture();
    }).mapEmpty();
}
```

should be replaced with

```java
private static Future<Void> connectToRedisCluster(Vertx vertx) {
  Redis redis = Redis.createClient(vertx, options);
  redisAPI = RedisAPI.api(redis);
  return Future.succeededFuture();
}
```

I've modified the reproducer to deploy 20 verticles and for each of them, run the loop 10_000 times. After updating the connection pool tunables to match the load, the test runs just fine, no errors.

**Comment by Ladicek** [comment]
I talked about this with @vietj and it turns out I was wrong. Sharing a connection between multiple contexts is a common pattern and the Vert.x Redis client doesn't support it properly.

What we should do is:
- remember the context on which the `NetSocket` was created (should already be there, but need to verify)
- on each request, verify if we're on the same context, and switch to the proper context if necessary (but need to create a context-bound promise before switching, so that the result is emitted on the original context)

**Comment by Ladicek** [comment]
#421 is the fix -- thanks @LangInteger for the reproducer!
