### ISSUE TITLE
Make usable from multiple contexts

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-redis-client#4]
The current service is not thread safe and makes the assumption that it is always accessed from same context.

We should make it usable from different contexts.

**Comment by PatrickSauts** [comment]
Is it thread safe now ? I'm having problems accessing it from different contexts

**Comment by pmlopes** [comment]
There was work done regarding this problem and it should be usable across contexts, however if you have an issue could you make a reproducer so we can investigate it further?

**Comment by Centaur** [comment]
@pmlopes Do you mean that we can use a single RedisClient instance for all request invoked from different threads?  I was looking for a connection pool for vertx-redis-client, if a single instance works, can we say that a connection pool is no longer necessary?

**Comment by pmlopes** [comment]
as of 3.3.1 using the client from any context has been tested and fixed. The client always works on pipeline mode so it can be shared across several verticles/handlers. If you're facing the i/o limits of a single connection then you can create several clients and round robin for example.
