### ISSUE TITLE
RedisClusterClient gives much higher load to first healthy node

### ISSUE THREAD

**Issue by Dieken** [vert-x3/vertx-redis-client#404]
https://github.com/vert-x3/vertx-redis-client/blob/9e88503327836e930ef616bbda8649c3ecfcf35b/src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java#L140

For each command `RedisClusterClient.connect()` always calls `getSlots()` to send command `CLUSTER SLOTS` to first healthy node,  thus the first healthy node has very high CPU usage,  in my benchmark test with Quarkus,  the first healthy node consumes 80% CPU and other nodes consume 30% CPU,  this leads to extra latency and uneven load on Redis cluster.

The `getSlots()` call should be cached and automatically periodically updated, or updated by `MOVED` response from Redis cluster.

**Comment by Dieken** [comment]
The code is hard to extract,  let me describe the call chain:

`@Inject ReactiveRedisDataSource` creates `ReactiveSortedSetCommandsImpl` and `ReactiveKeyCommandsImpl` instances,  all methods in these two classes call `AbstractRedisCommands.execute()`.

```
AbstractRedisCommands.execute()
   ReactiveRedisDataSourceImpl.execute()

      @Override
      public Uni<Response> execute(Request request) {
        if (connection != null) {
            return connection.send(request);
        }
        return redis.send(request);      // <-- reach here
    }


           ObservableRedis.send()
                RedisClusterClient.send()
                     BaseRedisClient.send()
                           RedisClusterClient.connect()   // reach second way above
```

So each command from `ReactiveSortedSetCommandsImpl` and `ReactiveKeyCommandsImpl`  triggers a call to `RedisClusterClient.connect()` which obtains a pooled `RedisConnection` and sends `CLUSTER SLOTS` command before the real original command.

**Comment by Dieken** [comment]
The high level ReactiveXxxCommands API has no chance to use withConnection() or batch(). I think it’s OK to obtain pooled connection for each command, the problem is Slots data should belong to RedisClusterClient as you described above, and the Slots data should be cached, never send “CLUSTER SLOTS” first for each Redis command.

**Comment by Ladicek** [comment]
You said you're `@Inject`-ing a `ReactiveRedisDataSource`, which has the `withConnection()` method. So it certainly is available to you. It probably isn't _useful_ to you, but that's hard to know for sure without seeing the code. Hence my other recommendation to descend to the direct Vert.x API (perhaps in the Mutiny variant), which is also available and provides more control.

I overall agree that the hash slot assignment should probably be stored in the `RedisClusterClient`, and I'll see what would it take to do it, but I'd like to hear from the experts too.

**Comment by Dieken** [comment]
I didn't use the low level API `ReactiveRedisDataSource`, I use the high level API `ReactiveXxxCommands`, the high level API doesn't have `withConnection()` method.

**Comment by Ladicek** [comment]
`ReactiveRedisDataSource` is not a low-level API, it is the Quarkus high-level API. You said that you use `@Inject ReactiveRedisDataSource` -- that's what I mean. There's a `withConnection()` method there.

 When I'm referring to low-level APIs, I'm talking about the Vert.x APIs (`Redis`, `RedisConnection`).

**Comment by Dieken** [comment]
My bad, the Quarkus guide does say `ReactiveRedisDataSource` is high level API: https://quarkus.io/guides/redis-reference#apis

**Comment by Dieken** [comment]
Checked the `ReactiveRedisDataSource.withConnection()` API again, if I create RedisXXXCommands instance in withConnection(), not in constructor of ReactiveEasy resource class as Quarkus Redis guide describes, the uneven load will be proportional to calls of withConnection not number of Redis command, that’s better but uneven load still exists, the Slots data still should be cached.

**Comment by Ladicek** [comment]
Yeah, I suspected as much. I'll see what I can do.

**Comment by Ladicek** [comment]
I'm trying to reproduce this locally, but I'm hitting a connection pooling issue (basically connection pooling doesn't seem to work at all) on the 4.x branch (`master` works fine), need to figure that out first. Just to let everyone know I'm working on this, though it might take a few days :-)

**Comment by Ladicek** [comment]
OK, so the connection pooling not working at all is #365 (and the fix is #374). This is currently scheduled for 5.0, which in my opinion is wrong -- we totally need to fix this in 4.x, otherwise Redis cluster is basically unusable. I can't see any possible downside to backporting the fix, it's just about adding `equals`/`hashCode` to 2 classes that are part of the key used to loookup the `Endpoint` (= connection pool) from `ConnectionManager`.

**Comment by Ladicek** [comment]
OK, so once I actually make the cluster client behave, this issue is fairly easy to reproduce with this simple Vert.x application:

```java
public class MainVerticle extends AbstractVerticle {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(new MainVerticle());
    }

    @Override
    public void start(Promise<Void> startPromise) {
        Redis redis = Redis.createClient(vertx, new RedisOptions()
                .setType(RedisClientType.CLUSTER)
                .setUseReplicas(RedisReplicas.SHARE)
                .setConnectionString("redis://192.168.1.171"));
        RedisAPI client = RedisAPI.api(redis);

        call(client, "foo", 0);
        call(client, "bar", 0);
        call(client, "baz", 0);
        call(client, "qux", 0);
        call(client, "quux", 0);
        call(client, "corge", 0);
        call(client, "grault", 0);
        call(client, "garply", 0);
        call(client, "waldo", 0);
        call(client, "fred", 0);
        call(client, "plugh", 0);
        call(client, "xyzzy", 0);
        call(client, "thud", 0);
    }

    private void call(RedisAPI client, String prefix, int last) {
        if (last == 1_000_000) {
            return;
        }
        int x = last + 1;
        client.set(List.of(prefix + x, "" + x))
                .flatMap(response -> {
                    return client.get(prefix + x);
                }).flatMap(response -> {
                    System.out.println(prefix + " --> " + response);
                    return client.set(List.of("__last__" + prefix, "" + x));
                }).onSuccess(response -> {
                    vertx.runOnContext(ignored -> call(client, prefix, x));
                }).onFailure(error -> {
                    System.out.println(error);
                });
    }
}
```

I'm using a simple 3-node cluster with 3 masters and no replicas. I run an actual virtual machine with 1 CPU and 1024 MB of RAM for each cluster node, so I can actually measure load average.

I made an interesting observation: when I tried to even the load on the cluster nodes by issuing the `CLUSTER SLOTS` command to a _random_ node (instead of always the first), I saw slightly increased load on the other nodes, but the first node had even higher load than before. This suggests that the other nodes forward the command to the first one (or something like that), but I'm no Redis cluster expert and didn't really look into the code. Anyway, this doesn't seem to be like a good strategy.

Next, I'll look into storing the hash slot assignment in the `RedisClusterClient` as mentioned above.

**Comment by Ladicek** [comment]
OK, storing hash slot assignment in the `RedisClusterClient` seems to work well. I'll submit a PR against `master`.

I'll also send 2 PRs to 4.x: backport of #374 and a backport of the fix for this issue.

**Comment by Ladicek** [comment]
PRs are up:

- #405 fixes this issue on `master`
- #406 backports #374 to `4.x`
- #407 backrpots #405 to `4.x`
