### ISSUE TITLE
redisClient.setBinaryWithOptions method is missing (ref jedis)

### ISSUE THREAD

**Issue by RichardHightower** [vert-x3/vertx-redis-client#41]
```java

        final SetOptions setOptions = new SetOptions();
        setOptions.setPX(expiry.toMillis());

        redisClient.setBinaryWithOptions(key, value,  setOptions, event -> {
            if (event.failed()) {
                confirmation.onError(event.cause());
            } else {
                confirmation.accept(true);
            }
        });
```

**Comment by pmlopes** [comment]
since we already have this API (although not a redis command) we should have the full implementation.

Note however that we do not use jedis or any other redis client underneath so do not assume that if an API exists on other drivers it should exist here.

**Comment by RichardHightower** [comment]
I know you are not using jedis. Jedis has this because it makes sense. I was referring to prior art. 

Redis does not make a distinction between text and binary with the set method. 
Java, Scala, JavaScript, Groovy, etc. do.

This is why we need a version of setBinary and setBinaryWithOptions that take a Vertx Buffer so that we can set binary data into Redis. 

See Jedis for prior art.

**Comment by RichardHightower** [comment]
nice
