### ISSUE TITLE
How to catch io.vertx.core.impl.NoStackTraceThrowable 

### ISSUE THREAD

**Issue by zclcs** [vert-x3/vertx-redis-client#425]
### Version
4.5.0

**Comment by zclcs** [comment]
![image](https://github.com/vert-x3/vertx-redis-client/assets/50291896/4f499ed6-65bd-4cf6-b182-ad2c913de1da)
![image](https://github.com/vert-x3/vertx-redis-client/assets/50291896/1cdef519-aa6d-4862-bc54-ccb8e0fcef6b)

**Comment by zclcs** [comment]
is virtual threads bug

**Comment by Ladicek** [comment]
`NoStackTraceThrowable` is not an `Exception` (nor an `Error`), so you need to catch `Throwable`.

This is arguably not the best user experience, but this behavior is inherited from Vert.x core.
