### ISSUE TITLE
Kryo serialization

### ISSUE THREAD

**Issue by PatrickSauts** [vert-x3/vertx-redis-client#45]
Any plan on using Kryo serializer.
It's one of the fastest.
https://github.com/eishay/jvm-serializers/wiki
https://code.google.com/p/kryo/

And unlike protobuff it doesn't need any pre configuration.

**Comment by pmlopes** [comment]
Kryo has no relation to redis. Redis has no need for serialization since it is a key store, any string or buffer should be all redis needs. If you want to replace json with kryo you need to do it at vert.x core level.
