### ISSUE TITLE
redis pool blocked

### ISSUE THREAD

**Issue by gillbates** [vert-x3/vertx-redis-client#474]
### Questions

Recently we are using redis for very heavy load and we found the current pooling may still block

### Version

4.5.9

### Do you have a reproducer?

running the code below, and we could always see sth will never finish ... anyone has ideas ?

```
List<Future<Void>> futureList = new ArrayList<>();
        for (int i = 0; i < 1000; i++) {
            int finalI = i;
            Future<Void> future = Future.succeededFuture()
                    .compose(v -> {
                        RedisOptions options = new RedisOptions()
                                .setConnectionString("redis://" + "127.0.0.1:6379");
                        Redis redis = Redis.createClient(Vertx.vertx(), options);
                        return redis.connect();
                    })
                    .compose(conn -> conn.send(Request.cmd(Command.PING)))
                    .map(reply -> {
                        log.debug("[{}] Redis ping: [{}] ...", finalI, reply.toString());
                        return null;
                    });
            futureList.add(future);
        }
        Future.join(futureList)
                .onComplete(res -> {
                    if (res.failed()) {
                        log.error("Redis ping failed: " + res.cause().getMessage());
                    }
                    System.exit(0);
                });
```

the code just get blocked at the 100th job

![CleanShot 2024-09-22 at 22 54 30@2x](https://github.com/user-attachments/assets/67693654-be02-41da-bdff-042aa7b85daf)

### Extra

* Oracle JDK 21, MAC M3.

**Comment by Ladicek** [comment]
Solved in https://discord.com/channels/751380286071242794/976770694731956264/1287442109485547573

The problem was that the code creates 1000 `Redis` objects and uses each to execute 1 command, instead of creating 1 `Redis` object and using it to execute 1000 commands.

**Comment by gillbates** [comment]
thx @Ladicek :)
it would be better that we have some Future<Redis> getConnection() method from vertx from the pespective of api design.
That would be more clear for busy developers :)
