### ISSUE TITLE
setWithOptions shall return a result of String type

### ISSUE THREAD

**Issue by brianjcj** [vert-x3/vertx-redis-client#50]
setWithOptions shall return a result of String type, install of Void. Otherwise it is no way to know the exact result when NX option is used.
SET command return string OK or (nil)

**Comment by pmlopes** [comment]
according to the docs: http://redis.io/commands/set

the new SET command can return both OK or nil (this should only apply when using options) so API for `setWithOptions` was wrong and should be fixed.
