### ISSUE TITLE
Is there a plan to support SSL connection?

### ISSUE THREAD

**Issue by hjianhao** [vert-x3/vertx-redis-client#53]
For production usage, we need to connect redis with SSL connection, but seems like vert.x's redis client not supporting this feature?

**Comment by pmlopes** [comment]
Redis does not support SSL see: http://redis.io/topics/security

It clearly states the server should be running in a trusted network and not publicly on the internet.

**Comment by chefhoobajoob** [comment]
@pmlopes : redis added tls support:
https://redis.io/topics/encryption
https://github.com/antirez/redis/pull/4855

...are there plans (or something already in the works) for supporting this in the client?

**Comment by pmlopes** [comment]
This is supported at least on master as the underlying socket can be configured to use TLS, or when using a connection string using the official protocol: `rediss://server`, note the double `s`.
