### ISSUE TITLE
About vertx-redis-client, the Pub/Sub mode

### ISSUE THREAD

**Issue by cet63** [vert-x3/vertx-redis-client#60]
### Version

* vert.x core:3.2.1
* vert.x redis client:3.2.1

* Jedis 2.7.3
* MSGPACK 0.6.11

### Context

I have a redis server for pub/sub.

Jedis  is used to publish byte[] message to the redis channel, 
and the byte array is produced by  MSGPACK .

When I received the published msg from the eventbus, I cannot decode the msg with MSGPACK .

After debugging, I think the problem encounted at class:
io.vertx.redis.impl.AbstractRedisClient,  
"case SUBSCRIBE: "   of  the send() method ,
the line: 
"
message.put("message", replyData[2].asType(String.class, encoding));
"

After vertx-redis-client "asType" the Buffer to String , I cannot convert the string to the byte array that can be decoded by MSGPACK.

### Steps to reproduce

1. Create a test pojo class, for example : 

public class TestPojo {

    private String[] aa;
    private int bb;
    private String cc;

...omit  the getter, setter 
}

2. Use msgpack encode the obj to  byte array:

        MessagePack packer = new MessagePack();
        packer.register(TestPojo.class);
        TestPojo to = new TestPojo();
        to.setAa(new String[]{"x1", "y2"});
        to.setBb(34);
        to.setCc("The Test Sentence!");

        byte[] msg = null;
        try {
            msg = packer.write(to);
        } catch (IOException e) {
            e.printStackTrace();
        }

3. Use the jedis client to publish the (byte[]) message:

        String channel = "test-channel";
        JedisPool pool = new JedisPool(new JedisPoolConfig(),  <redis_server_ip>,  <redis_server_port>);
        Jedis j = pool.getResource();
        j.publish(channel.getBytes("utf-8"), msg);

4. Use vertx-redis subscribe the channel, and consume the msg from eventbus : 

        vertx.eventBus().<JsonObject>consumer("io.vertx.redis" + channel , ar -> {
            JsonObject o = ar.body();
            String msg = o.getJsonObject("value").getString("message");
            
            MessagePack MSGPACK = new MessagePack();
            MSGPACK.register(TestPojo.class);
            try {
                TestPojo testObj = MSGPACK.read(msg.getBytes("utf-8"), TestPojo.class);
                System.out.println("---consumer, testObj:" + testObj.toString());
            } catch (IOException e) {
                e.printStackTrace();
            }

        });

5. Run the vertx program first, then publish a msg to redis, you will get a msgpack decode exception
"org.msgpack.MessageTypeException".

**Comment by pmlopes** [comment]
Given your exception can you compare the 2 byte arrays it does look like you're having an encoding issue, rather than a driver issue.

When dealing with binary content you should not use `UTF-8` encoding since due to its encoding format the conversion from `String` to `byte[]` might introduce extra bytes, as an example a `char` can be encoded in for example 4 `bytes`.

So when dealing with binary you should set the redis options not to use the default `UTF-8` encoding but `ISO-8859-1`. Using the latest will give you an `ASCII` like experience 1 `char` = 1 `byte`.

**Comment by cet63** [comment]
Thank you, pmlopes.
I will test the `ISO-8859-1` encoding  next monday and make feedback.

But why not return the binary data as a Buffer directly here?

**Comment by cet63** [comment]
Thank you, pmlopes.
The problem has been resloved according to your suggestion.

**Comment by pmlopes** [comment]
That would be an API improvement ;) there are 2 options: return the payload as base64 so the encoding is not an issue anymore; add an api to return a buffer directly but that will loose the metadata since it cannot be mixed with the binary payload

**Comment by cet63** [comment]
Thanks for your response,  :)

**Comment by pmlopes** [comment]
@cet63 if you have some time and want to make vert.x even better, feel free to propose a pull request ;)

**Comment by pmlopes** [comment]
There is now a option in RedisOptions to specify that messages to and from redis are binary. So all returned strings can safely be converted to/from byte[] without conversion issues.

**Comment by pmlopes** [comment]
Given that it is now possible to specify in the options that a strings should be handled as binary (ascii) I'll close this issue. The question about why not have byte[] as a type is open and cannot be answered right now for several reasons:

1. it will break the api
2. codegen will not recognize byte[]
3. redis itself works with utf8 strings so assuming that they are ASCII it is probably a bad practise
