### ISSUE TITLE
java.lang.ClassCastException: java.lang.Long cannot be cast to [Lio.vertx.redis.impl.Reply;

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-redis-client#61]
_From @hansen2014 on June 28, 2016 9:58_

RedisTransaction rtx = redisClient.transaction();

		rtx.multi(r -> {

			String setKey = RepositoryHelper.createKSKey("SessionScreenSymbol", clientCd, sessionId, viewNum);

			List<String> keyList = new ArrayList<>();
			for (String data : delS) {
				keyList.add(data);
				rtx.del(data, r1 -> {
					GLog.info("trans del executing ..., result: {} ", r1);
				});
			}

			if (delS.size() > 0) {
				rtx.sremMany(setKey, keyList, rst -> {
					GLog.info("trans strm executing ..., result: {}", rst);
				});
			}

			rtx.exec(handler);
		});

sometimes, will throw exception like that , and then, can not receive the reply. : 
fatal: Unhandled exception
java.lang.ClassCastException: java.lang.Long cannot be cast to [Lio.vertx.redis.impl.Reply;
	at io.vertx.redis.impl.Reply.asType(Reply.java:94)
	at io.vertx.redis.impl.Reply.asType(Reply.java:156)
	at io.vertx.redis.impl.RedisConnection.handleReply(RedisConnection.java:441)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:180)
	at io.vertx.redis.impl.ReplyParser.handle(ReplyParser.java:21)
	at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:312)
	at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$0(VertxNetHandler.java:67)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:357)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$0(OrderedExecutorFactory.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2016-06-28 17:57:57.558 [vert.x-eventloop-thread-7] ERROR EAGLE.DEFAULT - system error.
io.vertx.core.eventbus.ReplyException: Timed out after waiting 5000(ms) for a reply. address: 136
	at io.vertx.core.eventbus.impl.HandlerRegistration.sendAsyncResultFailure(HandlerRegistration.java:118) ~[vertx-core-3.3.0.jar:na]
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$new$0(HandlerRegistration.java:65) ~[vertx-core-3.3.0.jar:na]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:769) ~[vertx-core-3.3.0.jar:na]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:740) ~[vertx-core-3.3.0.jar:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359) ~[vertx-core-3.3.0.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339) ~[netty-common-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393) ~[netty-transport-4.1.1.Final.jar:4.1.1.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) ~[netty-common-4.1.1.Final.jar:4.1.1.Final]
	at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_91]

_Copied from original issue: eclipse/vert.x#1482_

**Comment by aneb01** [comment]
Hi pmlopes,

Probably same issue as the one we were having before https://groups.google.com/forum/#!topic/vertx/mG-jE3rYpw0

**Comment by pmlopes** [comment]
@aneb01 @hansen2014 the issue (at least from the reproducer from Yves) seems to be related to the lazy connect. As a quick workaround for it you can issue a ping command and wait for a reply before starting to hammering the server, once the connection is properly established the issue does not reproduce on my side. e.g.:

```java
public class Main {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        RedisOptions options = new RedisOptions();
        options.setHost("127.0.0.1");
        options.setPort(6379);

        Observable.range(1, 100)
                .subscribe(i -> {
                    RedisClient client = RedisClient.create(vertx, options);

                    client.ping(v -> {
                        System.out.println("start " + i);

                        Observable<Integer> ob = Observable.range(1, 100);

                        Observable<Long> set = ob.flatMap(r -> client.hsetObservable("key", "field", "value"));
                        Observable<String> get = ob.flatMap(r -> client.hgetObservable("key", "field"));
                        Observable<JsonArray> key = ob.flatMap(r -> client.hkeysObservable("key"));

                        Observable
                                .merge(set, key, get)
                                .finallyDo(() -> client.closeObservable().subscribe())
                                .subscribe();
                    });
                });
    }
}
```

As a proper fix I'll initiate the connection once the redis client object is created (the same way mongo client works).

Let me know if this solves your problem

**Comment by aneb01** [comment]
Many thanks.

I will try it out tomorrow morning and let you know.

**Comment by hansen2014** [comment]
@pmlopes  the problem still exists .

redisClient.ping(p -> {

				if (p.succeeded()) {

					RedisTransaction rtx = redisClient.transaction();

					rtx.multi(r -> {

						String setKey = RepositoryHelper.createKSKey("SessionScreenSymbol", clientCd, sessionId,
								viewNum);

						List<String> keyList = new ArrayList<>();
						for (String data : delS) {
							keyList.add(data);
							rtx.del(data, r1 -> {
								GLog.info("trans del executing ..., result: {} ", r1);
							});
						}

						if (delS.size() > 0) {
							rtx.sremMany(setKey, keyList, rst -> {
								GLog.info("trans strm executing ..., result: {}", rst);
							});
						}

						rtx.exec(handler);
					});

				} else {

					Future<JsonArray> rst = io.vertx.core.Future.failedFuture("ping problem");
					handler.handle(rst);

				}

			});

**Comment by aneb01** [comment]
In my project the problem is also still occurring. Strangely enough in my case the problem only occurs  when I am using one single redis client connection as a singleton for my application (shared throughout many verticles).  If I create a new redis client per verticle then this problem does not, anymore (as it did in the past), occur.

Maybe I better  wait until hansen2014's problem is fixed and try it again so I can make sure if it is indeed the same problem or not.  

Maybe same error but different cause.

**Comment by pmlopes** [comment]
@aneb01 and @hansen2014 could you guys verify https://github.com/vert-x3/vertx-redis-client/pull/62 that it also works for you?

I've been load testing with several scenarios:

* 1, 8, 32 event loops
* 1 Verticle 1, 8 instances
* 1, 100 clients per verticle

I don't see the issue anymore but you guys have different scenarios maybe I still missed something

**Comment by aneb01** [comment]
I ran some quick tests and it seems that the issue is fixed for me. No more class cast exceptions are being thrown.

Seems fixed to me.  Thank you very much.

**Comment by hansen2014** [comment]
@pmlopes  so sorry,  i used the version 3.3.1-SNAPSHOT for test, but the same exception occured , about one-tenth.

**Comment by pmlopes** [comment]
@hansen2014 can you then provide me a full working example showing the problem, I was using @aneb01 example to reproduce the issue and his case is solved, i guess that you are using the client in a different way that we haven't thought about...

I don't need you application just a a simple verticle that uses the redis client and if we do a big loop or something shows your problem.

**Comment by hansen2014** [comment]
@pmlopes it seems that RedisClient can not be used in Worker Verticle . I changed other way , the problem no more appear. Thank you very much .

**Comment by pmlopes** [comment]
@hansen2014 worker verticles are supposed to be used when you are working with blocking APIs which will then delegate to a thread pool for execution. If you're interested in the best performance you should try to avoid them.

Indeed since redis client is async that scenario was never considered and/or tested. I'll try to run some worker verticle tests and see if there is something I can do to improve interop there and post the results.

**Comment by pmlopes** [comment]
My worker tests also seem to work fine:

```java
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;

public class Main {
    public static void main(String[] args) throws Exception {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(MyVerticle.class.getName(), new DeploymentOptions().setWorker(true));
    }
}
```

```java
import io.vertx.core.AbstractVerticle;
import io.vertx.core.json.JsonArray;
import io.vertx.rxjava.core.Vertx;
import io.vertx.rxjava.redis.RedisClient;
import rx.Observable;

public class MyVerticle extends AbstractVerticle {
    @Override
    public void start() {
        Vertx vertx = new Vertx(getVertx());

        Observable.range(1, 100)
                .subscribe(i -> {

                    System.out.println("start " + i);
                    RedisClient client = RedisClient.create(vertx);

                    Observable<Integer> ob = Observable.range(1, 100);

                    Observable<Long> set = ob.flatMap(r -> client.hsetObservable("key", "field", "value"));
                    Observable<String> get = ob.flatMap(r -> client.hgetObservable("key", "field"));
                    Observable<JsonArray> key = ob.flatMap(r -> client.hkeysObservable("key"));

                    Observable
                            .merge(set, key, get)
                            .finallyDo(() -> client.closeObservable().subscribe())
                            .subscribe();
                });

    }
}
```

@hansen2014  if you can modify this to show the error, we'll continue otherwise we'll consider the issue as fixed.

**Comment by hansen2014** [comment]
sorry , i make a mistake,  it can not used in multi-threaded worker verticle. the exceptio like that:

`java.lang.IllegalStateException: Cannot use NetClient in a multi-threaded worker verticle
	at io.vertx.core.net.impl.NetClientImpl.<init>(NetClientImpl.java:85)
	at io.vertx.core.net.impl.NetClientImpl.<init>(NetClientImpl.java:69)
	at io.vertx.core.impl.VertxImpl.createNetClient(VertxImpl.java:225)
	at io.vertx.redis.impl.AbstractRedisClient.<init>(AbstractRedisClient.java:52)
	at io.vertx.redis.impl.RedisClientImpl.<init>(RedisClientImpl.java:1466)
	at io.vertx.redis.RedisClient.create(RedisClient.java:50)
	at com.linkstec.raptor.eagle.push.subscribe.UnsubscribeVerticle.lambda$1(UnsubscribeVerticle.java:114)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$1(EventBusImpl.java:334)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:213)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:192)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:499)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

before: DeploymentOptions opt = new DeploymentOptions().setWorker(true).setMultiThreaded(true); the error occured.

noe : DeploymentOptions opt = new DeploymentOptions().setWorker(true); is ok.

**Comment by aneb01** [comment]
For what it's worth: I also use vertx-redis-client in worker verticles and that does not seem to give any problems. I do remember that the multi threaded setting @hansen2014 mentioned gave problems in the past. However currently I am not using that anymore. 

Slightly off topic: Paulo your comment about the worker verticles made me rethink my implementation though and wonder my I started using worker verticles in the first place.  Somehow I got it into my head that doing something like this does actually block the main thread:

basically waiting for an eventBus.send message reply

- httpServer.websocket.handler(onReceiveMessage(message)
- onReceiveMessage: eventBus.send("...",message) --> send message to a message processor verticle
- message processor verticle: eventBus.consume("..",message), use redis client to store or retrieve something and when finished, by callback or rx, do a message reply
- do something when receiving the callback for the initial eventbus.send

maybe I just misinterpreted the message timeout errors I was getting in the past with actual main thread blocking errors.

Either way off topic.

**Comment by pmlopes** [comment]
All Vert.x handlers are async by nature and won't block the eventloop, blocking methods are clearly labelled as so, e.g. on the filesystem object you have: `createFileBlocking` to denote that this variant is blocking.

Redis client is also 100% async, no non-blocking.

Message timeouts are not related to main thread being blocked, as you noted it is just a control that a reply was not received on time. That can be either configured on the delivery options `sendTimeout` or in your sockjs bridge if you're using it.

**Comment by aneb01** [comment]
Thanks for the fast feedback as always.

**Comment by pmlopes** [comment]
@hansen2014 ok, the multi thread exception is not related to this issue. You can work around it if you really need to use multi thread. Deploy your redis client and I/O operations as a standard verticle and register some address on the event bus. Then from your blocking (worker) multithreaded code you can send messages to the event bus that are delivered to the async verticle.
