### ISSUE TITLE
can't continue subscribe while reconnected

### ISSUE THREAD

**Issue by fooevr** [vert-x3/vertx-redis-client#69]
### Version

* vert.x core:3.3.3
* vert.x redis client:3.3.3

### Context

can't continue subscribe while reconnected, or how to handle connection's reconnect event?

**Comment by tenitram** [comment]
I have got the same issue. Steps to reproduce:

Redis client configured setup for pub-sub mode. Everything works perfectly - events are being passed to sub. After I stop redis for a second, start it again, then sub part is not receiving events, but pub is not failing:

`redisPub.publish("web-notify", messageBody, res -> {
    if(res.failed()){
        LOG.error(res.cause());
     }
});`

No ERROR log entry, nor message delivered. Its quite important for production system - Blocker for using pub sub mode I'd say.
