### ISSUE TITLE
Fail more gracefully if start is not called

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-redis-client#7]
If you don't call `start` on the service before performing any operation, you get a strange behaviour.

For example with `scriptLoad` you'll get a NPE because encoding is not set (it must be set in the start method).

Here's a simple reproducer : https://github.com/aesteve/redis-client-bug

The working code is commented, if you run the main verticle it throws a NPE.

**Comment by purplefox** [comment]
The start method no longer exists so closing
