### ISSUE TITLE
setex takes ttl as a long, expire as an int

### ISSUE THREAD

**Issue by jebbench** [vert-x3/vertx-redis-client#71]
### Version

* vert.x core: 3.3.3
* vert.x redis client: 3.3.3

### Context
The `setex` method requires that the number of seconds until expiry is provided as a `long` however the `expire` method requires an `int`; maybe there's a good reason for this that I'm missing but it seems inconsistent (in my case I have a object with a `getTtl` method which returns a long (I used `setex` first) but I'm having to cast the result to pass into `expire`).

**Comment by pmlopes** [comment]
That is an API inconsistency bug. Redis integers are always 64bit long, so all integer values in the API should of of java type `long`
