### ISSUE TITLE
Performance issues when huge results / command args 

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-redis-client#72]
### Version

* vert.x core: 3.3.3
* vert.x redis client: 3.3.3

### Context

800000 keys in Redis. Single core. Single Verticle instance. Single HTTP request.
Keys are :  ` 25.1234567` (two numbers separated by a dot)

First use case (for the sake of the example I'm omitting the async part) : 
`JsonArray theKeys = redis.scan("25.*")` => returns the 800000 keys (in real life there'll be more than 800000... under `26.1234567` for instance).
Then `JsonArray theValues = mgetmany(theKeys)`
I tried with both `vertx-redis-client` and `jedis` and there's a huge difference between both.

Second use case : 

(Originally to see if `scan`was the issue)

I added every "second part of the key" in a sorted set with this key as score (and fake values, unique though) 
Thus, the "full listing" becomes : 
` JsonArray items = redis.zrangebyscore("thekeys", 0, 1000000, ...)`
And then, the same `mgetMany` as as in the first case scenario.

I measured the time of the `zrangebyscore` between jedis and vertx-redis and the results are stunning : 
- 3s (which is huge...) for Jedis
- 23s for vertx-redis-client

### Do you have a reproducer?

I'm in the process of creating one, just wanted to warn you asap.

### Steps to reproduce

1. Insert a million values in a Redis sorted set
2. Try to `zrangebyscore` the whole sorted set with vertx-redis
3. Use the resulting JsonArray to perform another Redis operation
4. In the meantime, watch `slowlog` on the Redis server. You'll see Redis doesn't see "such big durations"

### Extra

* I was digging through `slowlog` when I realized Redis wasn't seeing long durations at all. So it's all on Vert.x marshalling / unmarshalling part.
* I'll try to create a full reproducer, performing the inserts, then "benchmarking" jedis vs. vertx-redis in both cases mentionned above
* I think JMH should be involved in the process to see if JSON marshalling is the issue ?
* I opened this issue just for you to be informed about my experiments

Hope we can investigate together.

**Comment by pmlopes** [comment]
For large datasets you should avoid hmgetall because it will perform a transformation from redid list to json.

**Comment by aesteve** [comment]
Thanks @pmlopes .

So, just to be clear, in my case (`zrangebyscore` returning a lot of records, not `hmgetall`) it is expected to be causing issues with JSON marshalling / unmarshalling.

If not please re-open the issue ;) 

I'll try to find another asynchronous solution (either re-mapping, or attacking redis directly, idk).

Thanks for confirming.
