### ISSUE TITLE
Operation mgetBinary

### ISSUE THREAD

**Issue by KlausLR** [vert-x3/vertx-redis-client#82]
### Version

* vert.x core: 3.4.2
* vert.x redis client: 3.4.2

### Context

The redis-operation "mget" accepts many keys and can handle binary data. I am missing a "get binary data for multiple keys"-operation in vertx-redis-client (for performance reasons, I don't want to have a loop with 'getBinary'). Is it out of scope to implement that? Or is there a workaround with some encoding magic?

### Do you have a reproducer?

This is related to https://github.com/vert-x3/vertx-redis-client/issues/40. I created a test with mget that fails for binary data. An operation "mgetManyBinary" that makes this test green would be great.
Add this to RedisClientTestBase.java:
  
`@Test`
`  public void testMgetBinary() {`
`    final String mykey = makeKey();`
`    final byte[] binary_data = {0,1,127,-1,-128};`
`    redis.setBinary(mykey, Buffer.buffer(binary_data), reply0 ->{`
`      assertTrue(reply0.succeeded());`
`      redis.mgetMany(toList(mykey),reply1 ->{`
`        assertTrue(reply1.succeeded());`
`        assertArrayEquals(binary_data,reply1.result().getString(0).getBytes());`
`        testComplete();`
`      });`
`    });`
`    await();`
`  }`

**Comment by pmlopes** [comment]
4.0.0 milestone 4 uses buffers and avoids serialization, please test with it and reopen if needed.
