### ISSUE TITLE
Expand binary support for Redis

### ISSUE THREAD

**Issue by jenyad20** [vert-x3/vertx-redis-client#83]
### Version

* vert.x core: 3.4.2
* vert.x redis client: 3.4.2

### Context
We are using Redis to store constantly incoming binary data, storing it to file is not an option since there might be race conditions and information will be lost. The only append function Redis currently have is for String. Since you have setBinary function I figured I can get the current data in form of Buffer using getBinary function, append to the buffer and use setBinary, but to avoid race condition I must use transaction.multi, and thats where the biggest issue is, ## getBinary in RedisClient class returns a Buffer, but getBinary in RedisTransaction class returns a String. Converting byte [] to String ruins the data so its not an option.

**Comment by vietj** [comment]
it does not seem consistent indeed.

**Comment by vietj** [comment]
@pmlopes should we change `String` to `Buffer` for `RedisTransaction#getBinary` and `RedisTransaction#setBinary` ?

**Comment by jenyad20** [comment]
@vietj 
If you could also also expend the append functions so they include append binary, and also the option to append with parameters, when I set a string i can choose expiration time, but if I append I have to use another command for expiration. I would do it myself but you made the RedisClientImpl class final, which means I can only copy-paste it, creating code duplication and poor support for future versions. 
It would also help a lot if I can just access the send, sendLong and toPayload methods but those are either private or package-private. Being able to use them would make the api much less limited.

**Comment by pmlopes** [comment]
I believe @jenyad20 is aiming for something like: https://github.com/vert-x3/vertx-redis-client/issues/68 the idea there is to make a really simple client that can only send messages and does not try to map each single command to an method in the java interface, basically a pure wrapper around `toPayload`

**Comment by jenyad20** [comment]
@pmlopes I like the current API, its very straight forward, simple to use and easy to learn, what I'm hoping for is for the implementations not to be final and the methods I mentioned to become public, this will make the API much less limited.

Do you have any idea when will the version 3.5.0 will come out? We need to release the alpha version of our product soon, can you suggest a work around if I need to append binary data to key?
