### ISSUE TITLE
Shouldn't zcount use strings instead of Doubles ?

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-redis-client#85]
### Version

* vert.x core: 3.4.2
* vert.x redis client: 3.4.2

### Context

The documentation for [ZCOUNT](https://redis.io/commands/zcount) states that 

> The min and max arguments have **the same semantic** as described for ZRANGEBYSCORE.

Hence, the arguments in method `zcount` should probably have the same type as the arguments of `zrangebyscore` (which are strings)

Note that it's still possible to count using `-inf`, `+inf`, by using `Double.NEGATIVE_INFINITY`, `Double.POSITIVE_INFINITY`. 
=> So this is definitely **not a blocking issue**, but more an opened question : 

Since the Redis documentation states that `zcount` and `zrangebyscore` have the same arguments, shouldn't we use the same parameter types ?

**Comment by telecoder** [comment]
With `double` arguments it is not possible to use exclusive intervals such as:

`ZCOUNT myset (1 5`

**Comment by pmlopes** [comment]
All command helpers are now built from redis `COMMAND` metadata.
