### ISSUE TITLE
Support for Unix sockets

### ISSUE THREAD

**Issue by ankushs92** [vert-x3/vertx-redis-client#90]
Hey guys,
We've been using vertx-redis-client for a while in production now, and so far everything is great. 
We are currently exploring libraries that provide support for connecting to Redis via Unix sockets. Any plans on providing this feature in the near future?

**Comment by vietj** [comment]
@ankushs92 Vert.x 3.5 provides support for Unix domain sockets and the actual Redis client uses a NetClient, however it does not expose the domain socket setting but it should be easy to achieve, would you mind to contribute such feature ?

**Comment by BillyYccc** [comment]
I made a PR to enable the domain socket option in Redis client.

**Comment by pmlopes** [comment]
Fixed by #91
