### ISSUE TITLE
Undocumented breaking change: removal of public method RedisOptions.toJSON

### ISSUE THREAD

**Issue by chrismcnair** [vert-x3/vertx-redis-client#96]
### Version

* vert.x core: 3.5.0
* vert.x redis client: 3.5.0

### Context

My code, which previously used vertx-core 3.4.1 and vertx-redis-client 3.4.1, used the `RedisOptions#toJSON` method to convert `RedisOptions` to a vertx `JsonObject`.

It seems that https://github.com/vert-x3/vertx-redis-client/commit/87efcd336bea3e2a0e5561027861605c964811fa#diff-4f866cf08c9c25e62bbbf684dcf7d55cL301 introduces a breaking change to the `RedisOptions` API, removing the `toJSON` method. I could not find this change listed in any of the release docs or breaking changes docs. 

### Do you have a reproducer?

n/a

### Steps to reproduce

n/a

### Extra

I am curious if this is an intentional breaking change and if it is documented anywhere.

**Comment by pmlopes** [comment]
Sorry, this wasn't an intentional breakage, since we already had a couple of releases after 3.4.1 I'll mark the issue as won't fix and it would be now a bit too late to add the method back and mark it as deprecated.
