### ISSUE TITLE
Memory leak when connect fails

### ISSUE THREAD

**Issue by ksundaresan** [vert-x3/vertx-redis-client#97]
### Version

* vert.x core: 3.4.2
* vert.x redis client: 3.4.2

### Context

I got an Out of Memory issue, because of too many items in closeHooks were there. It seems that in the RedisConnection.connect(), when the NetClient.connect fails to connect, the NetClient is not closed. This may cause the closeHook added to vertx context by the NetClientImpl is never been removed and builds up over a period. 

### Extra
The issue seems to be similar to the one that was fixed in vertx-proton https://github.com/vert-x3/vertx-proton/issues/51

**Comment by vietj** [comment]
perhaps we should also check the MQTT client as well ? cc @ppatierno @Sammers21

**Comment by vietj** [comment]
assigned to you @pmlopes feel free to reassign to a contributor

**Comment by kagof** [comment]
I've addressed this with a one line fix here: https://github.com/kagof/vertx-redis-client/commit/92200e8b32156ee25a5ce55816be524225bfaa0f

Happy to open a PR if you would like.

**Comment by vietj** [comment]
have you signed the Eclipse Contributor Agreement @ksundaresan ?

**Comment by vietj** [comment]
I can't see a way to test this right now.

**Comment by vietj** [comment]
@pmlopes is there any reason the NetClient cannot be part instead of `BaseRedisClient` ?
